//! Tolerant reader for G-code produced by other slicers and firmware flavors.
//! It recovers movements, layers and totals for preview; it does not validate
//! a file for printing; volume uses the supplied, declared or default filament diameter.

use crate::foreign_extrusion::Extrusion;
use crate::foreign_feedrate::Feedrate;
use crate::foreign_words::{
    self,
    Command::{G, InvalidTool, M, T},
};
use crate::{
    GcodeBounds, GcodeMove, GcodePreview, MAX_LAYERS, MAX_LINE_BYTES, MAX_MOVES,
    MAX_OUTPUT_BYTES, Result, invalid, number, valid_coordinate,
};
use std::borrow::Cow;

/// Default filament diameter when a foreign file declares none.
pub const ASSUMED_FILAMENT_DIAMETER_MM: f64 = 1.75;
const MAX_ARC_SEGMENTS: usize = 64;
const ARC_SEGMENT_MM: f64 = 1.0;

/// Slicer family recognized from header comments.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Generator {
    PrusaSlicer,
    OrcaSlicer,
    BambuStudio,
    SuperSlicer,
    Cura,
    Slic3r,
    Simplify3D,
    IdeaMaker,
    KiriMoto,
    OpenScadViewer,
    Unknown,
}

impl Generator {
    pub fn name(self) -> &'static str {
        match self {
            Generator::PrusaSlicer => "PrusaSlicer",
            Generator::OrcaSlicer => "OrcaSlicer",
            Generator::BambuStudio => "BambuStudio",
            Generator::SuperSlicer => "SuperSlicer",
            Generator::Cura => "Cura",
            Generator::Slic3r => "Slic3r",
            Generator::Simplify3D => "Simplify3D",
            Generator::IdeaMaker => "ideaMaker",
            Generator::KiriMoto => "Kiri:Moto",
            Generator::OpenScadViewer => "open-scad-viewer",
            Generator::Unknown => "unknown",
        }
    }
}

/// Header-level facts about a file, gathered without executing motion.
#[derive(Clone, Debug, PartialEq)]
pub struct DialectInfo {
    pub generator: Generator,
    /// Firmware flavor declared by the slicer (`;FLAVOR:`, `; gcode_flavor =`), if any.
    pub flavor: Option<String>,
    pub filament_diameter_mm: Option<f64>,
    /// True when the file is one of this crate's own strict dialects.
    pub native: bool,
}

/// Inspects the first lines and slicer footer for generator and flavor hints.
pub fn detect(gcode: &str) -> DialectInfo {
    let mut info = DialectInfo {
        generator: Generator::Unknown,
        flavor: None,
        filament_diameter_mm: None,
        native: false,
    };
    let first = gcode.lines().next().unwrap_or("").trim();
    if first == format!("; {}", crate::DIALECT) || first == format!("; {}", crate::JOB_DIALECT) {
        info.native = true;
        info.generator = Generator::OpenScadViewer;
    }
    let head = gcode.lines().take(64);
    let tail_start = gcode.len().saturating_sub(64 * 1024);
    let tail_start = (tail_start..=gcode.len())
        .find(|i| gcode.is_char_boundary(*i))
        .unwrap_or(gcode.len());
    let tail = gcode[tail_start..].lines();
    for raw in head.chain(tail) {
        let line = raw.trim();
        if !line.starts_with(';') {
            continue;
        }
        let comment = line.trim_start_matches(';').trim();
        let lower = comment.to_ascii_lowercase();
        if info.generator == Generator::Unknown {
            info.generator = if lower.contains("generated by prusaslicer") {
                Generator::PrusaSlicer
            } else if lower.contains("generated by orcaslicer") {
                Generator::OrcaSlicer
            } else if lower.contains("generated by bambustudio")
                || lower.contains("generated by bambu studio")
            {
                Generator::BambuStudio
            } else if lower.contains("generated by superslicer") {
                Generator::SuperSlicer
            } else if lower.contains("generated with cura") {
                Generator::Cura
            } else if lower.contains("generated by slic3r") {
                Generator::Slic3r
            } else if lower.contains("simplify3d") {
                Generator::Simplify3D
            } else if lower.contains("ideamaker") {
                Generator::IdeaMaker
            } else if lower.contains("kiri:moto") || lower.contains("kirimoto") {
                Generator::KiriMoto
            } else {
                Generator::Unknown
            };
        }
        if info.flavor.is_none() {
            if let Some(value) = comment.strip_prefix("FLAVOR:") {
                info.flavor = Some(value.trim().to_string());
            } else if let Some(value) = lower
                .strip_prefix("gcode_flavor =")
                .or_else(|| lower.strip_prefix("gcode_flavor="))
            {
                info.flavor = Some(value.trim().to_string());
            }
        }
        if info.filament_diameter_mm.is_none()
            && let Some(text) = diameter_field(comment, &lower)
            && let Ok(value) = number(text)
            && value > 0.0
            && value <= 10.0
        {
            info.filament_diameter_mm = Some(value);
        }
    }
    info
}

/// Slicer-specific filament diameter fields; returns the raw value text.
fn diameter_field<'a>(comment: &'a str, lower: &str) -> Option<&'a str> {
    const KEYS: [&str; 5] = [
        "filament_diameter_mm:",
        "filament_diameter =",
        "filament_diameter=",
        "filament diameter =",
        "filamentdiameter,",
    ];
    let key = KEYS.iter().find(|key| lower.starts_with(*key))?;
    let value = comment[key.len()..].split([',', ';']).next()?.trim();
    Some(value)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Plane {
    Xy,
    Other,
}

struct Machine {
    position: [f64; 3],
    known: [bool; 3],
    extrusion: Extrusion,
    /// Relative XYZ (`G91`).
    relative: bool,
    /// Relative E (`M83` or `G91` without `M82`).
    relative_e: bool,
    inches: bool,
    feedrate: Feedrate,
    plane: Plane,
}

impl Machine {
    fn scale(&self) -> f64 {
        if self.inches { 25.4 } else { 1.0 }
    }
}

struct Layers {
    explicit_markers: bool,
    count: usize,
    current_z: Option<f64>,
    /// Z levels at which extrusion happened, for the inferred-layer fallback.
    printed_z: Vec<f64>,
}

impl Layers {
    fn index_for(&mut self, z: f64, extruding: bool) -> Result<usize> {
        if self.explicit_markers {
            return Ok(self.count.saturating_sub(1));
        }
        if !extruding {
            return Ok(self.printed_z.len().saturating_sub(1));
        }
        match self.printed_z.last() {
            Some(last) if (*last - z).abs() < 1e-6 => Ok(self.printed_z.len() - 1),
            _ => {
                if self.printed_z.len() == MAX_LAYERS {
                    return Err(invalid(
                        "GCODE_LAYER_LIMIT",
                        "G-code exceeded 2048 inferred layers",
                    ));
                }
                if let Some(position) = self.printed_z.iter().position(|v| (*v - z).abs() < 1e-6) {
                    return Ok(position);
                }
                self.printed_z.push(z);
                Ok(self.printed_z.len() - 1)
            }
        }
    }
}

fn axis_word(token: &str) -> Result<(u8, f64)> {
    if token.len() < 2 || !token.is_ascii() {
        return Err(invalid("GCODE_SYNTAX", "Expected axis/value words"));
    }
    let axis = token.as_bytes()[0].to_ascii_uppercase();
    if !axis.is_ascii_alphabetic() {
        return Err(invalid("GCODE_SYNTAX", "Expected axis/value words"));
    }
    Ok((axis, number(&token[1..])?))
}

fn axis_words<'a>(rest: impl Iterator<Item = &'a str>) -> Result<Vec<(u8, f64)>> {
    rest.map(axis_word).collect()
}

#[derive(Default)]
struct MotionWords {
    xyz: [Option<f64>; 3],
    e: Option<f64>,
    f: Option<f64>,
    i: Option<f64>,
    j: Option<f64>,
    r: Option<f64>,
}

impl MotionWords {
    fn parse<'a>(rest: impl Iterator<Item = &'a str>) -> Result<Self> {
        let mut out = Self::default();
        for token in rest {
            let (axis, value) = axis_word(token)?;
            match axis {
                b'X' => out.xyz[0] = Some(value),
                b'Y' => out.xyz[1] = Some(value),
                b'Z' => out.xyz[2] = Some(value),
                b'E' => out.e = Some(value),
                b'F' => out.f = Some(value),
                b'I' => out.i = Some(value),
                b'J' => out.j = Some(value),
                b'R' => out.r = Some(value),
                _ => {}
            }
        }
        Ok(out)
    }
}

fn word(words: &[(u8, f64)], axis: u8) -> Option<f64> {
    words
        .iter()
        .rev()
        .find(|(a, _)| *a == axis)
        .map(|(_, v)| *v)
}

/// Parses layer marker comments from common slicers. Returns true when a layer starts.
fn layer_marker(comment: &str) -> bool {
    let upper = comment.trim().to_ascii_uppercase();
    upper.starts_with("LAYER:")
        || upper.starts_with("LAYER_CHANGE")
        || upper.starts_with("LAYER ")
        || upper == "LAYER"
        || upper.starts_with("BEGIN_LAYER_OBJECT")
        || (upper.starts_with("LAYER ") && upper.contains(", Z ="))
}

fn has_layer_markers(gcode: &str) -> bool {
    gcode
        .lines()
        .filter_map(|line| line.trim().strip_prefix(';'))
        .any(layer_marker)
}

/// Tolerant preview of arbitrary FDM G-code. Unknown commands are skipped;
/// malformed motion words, arcs outside XY, and resource limits are errors.
pub fn parse_foreign(gcode: &str) -> Result<GcodePreview> {
    parse_foreign_with(gcode, None)
}

/// Like [`parse_foreign`], with an explicit filament diameter overriding the header.
pub fn parse_foreign_with(gcode: &str, filament_diameter_mm: Option<f64>) -> Result<GcodePreview> {
    if gcode.len() > MAX_OUTPUT_BYTES {
        return Err(invalid("GCODE_OUTPUT_LIMIT", "G-code exceeds 4 MiB"));
    }
    let info = detect(gcode);
    let diameter = filament_diameter_mm
        .or(info.filament_diameter_mm)
        .unwrap_or(ASSUMED_FILAMENT_DIAMETER_MM);
    let mut result = GcodePreview {
        layers: 0,
        extrusion_mm: 0.0,
        deposited_volume_mm3: 0.0,
        moves: Vec::new(),
        bounds: None,
        travel_distance_mm: 0.0,
        print_distance_mm: 0.0,
        estimated_time_s: 0.0,
    };
    let mut machine = Machine {
        position: [0.0; 3],
        known: [false; 3],
        extrusion: Extrusion::new(diameter)?,
        relative: false,
        relative_e: false,
        inches: false,
        feedrate: Feedrate::default(),
        plane: Plane::Xy,
    };
    let mut layers = Layers {
        explicit_markers: has_layer_markers(gcode),
        count: 0,
        current_z: None,
        printed_z: Vec::new(),
    };
    let mut move_count = 0usize;
    for (line_index, raw) in gcode.lines().enumerate() {
        let line_result: Result<()> = (|| {
            if raw.len() > MAX_LINE_BYTES {
                return Err(invalid(
                    "GCODE_LINE_LIMIT",
                    "G-code line exceeds 1024 bytes",
                ));
            }
            let line = raw.trim();
            if line.is_empty() {
                return Ok(());
            }
            let (command_text, comment) = match line.find(';') {
                Some(index) => (&line[..index], Some(&line[index + 1..])),
                None => (line, None),
            };
            if let Some(comment) = comment
                && command_text.trim().is_empty()
                && layers.explicit_markers
                && layer_marker(comment)
            {
                if layers.count == MAX_LAYERS {
                    return Err(invalid("GCODE_LAYER_LIMIT", "G-code exceeded 2048 layers"));
                }
                layers.count += 1;
                layers.current_z = None;
                return Ok(());
            }
            let cleaned = foreign_words::code(line);
            let mut rest = foreign_words::words(&cleaned).peekable();
            let Some(command) = rest.next() else {
                return Ok(());
            };
            let canonical = foreign_words::command(command);
            match canonical {
                G(20) => machine.inches = true,
                G(21) => machine.inches = false,
                G(90) => {
                    machine.relative = false;
                    machine.relative_e = false;
                }
                G(91) => {
                    machine.relative = true;
                    machine.relative_e = true;
                }
                M(82) => machine.relative_e = false,
                M(83) => machine.relative_e = true,
                M(220) => machine.feedrate.configure(rest)?,
                M(200) => {
                    let words = axis_words(rest)?;
                    machine.extrusion.configure_volume(
                        word(&words, b'D'),
                        word(&words, b'S'),
                        word(&words, b'T'),
                        machine.scale(),
                    )?;
                }
                M(221) => {
                    let words = axis_words(rest)?;
                    if word(&words, b'D').is_some() {
                        return Err(invalid(
                            "GCODE_UNSUPPORTED_COMMAND",
                            "M221 D extruder selectors are not supported; this preview uses Marlin-style T selectors",
                        ));
                    }
                    machine
                        .extrusion
                        .configure_flow(word(&words, b'S'), word(&words, b'T'))?;
                }
                T(tool) => machine.extrusion.select_tool(tool)?,
                InvalidTool => {
                    return Err(invalid(
                        "GCODE_INVALID_SETTINGS",
                        "Extruder identifier must be an unsigned 32-bit integer",
                    ));
                }
                G(17) => machine.plane = Plane::Xy,
                G(18) | G(19) => machine.plane = Plane::Other,
                G(92) => {
                    let words = axis_words(rest)?;
                    if words.is_empty() {
                        machine.extrusion.reset(0.0, machine.scale())?;
                        machine.position = [0.0; 3];
                    }
                    for (axis, value) in words {
                        match axis {
                            b'X' => machine.position[0] = value * machine.scale(),
                            b'Y' => machine.position[1] = value * machine.scale(),
                            b'Z' => machine.position[2] = value * machine.scale(),
                            b'E' => machine.extrusion.reset(value, machine.scale())?,
                            _ => {}
                        }
                    }
                }
                G(28) => {
                    if rest.peek().is_none() {
                        machine.known = [false; 3];
                    } else {
                        for token in rest {
                            let axis = token.as_bytes()[0].to_ascii_uppercase();
                            if let Some(index) = b"XYZ".iter().position(|a| *a == axis) {
                                // Homing origin depends on the machine, so it is unknown here.
                                machine.known[index] = false;
                            }
                        }
                    }
                }
                G(0..=3) => {
                    move_count += 1;
                    if move_count > MAX_MOVES {
                        return Err(invalid("GCODE_MOVE_LIMIT", "G-code exceeded 100000 moves"));
                    }
                    let words = MotionWords::parse(rest)?;
                    let scale = machine.scale();
                    if let Some(f) = words.f {
                        machine.feedrate.set(f * scale)?;
                    }
                    let old_position = machine.position;
                    let was_known = machine.known.iter().all(|v| *v);
                    let mut target = machine.position;
                    for (index, value) in words.xyz.iter().enumerate() {
                        if let Some(value) = value {
                            let value = value * scale;
                            target[index] = if machine.relative {
                                machine.position[index] + value
                            } else {
                                value
                            };
                            if !valid_coordinate(target[index]) {
                                return Err(invalid(
                                    "GCODE_INVALID_COORDINATE",
                                    "Move coordinates must be within +/-1000000 mm",
                                ));
                            }
                            machine.known[index] = true;
                        }
                    }
                    let extruded =
                        machine
                            .extrusion
                            .advance(words.e, machine.relative_e, scale)?;
                    let is_arc = matches!(canonical, G(2) | G(3));
                    let has_axis = is_arc || words.xyz.iter().any(Option::is_some);
                    if !has_axis && words.e.is_none() {
                        return Ok(());
                    }
                    let is_known = machine.known.iter().all(|v| *v);
                    let feedrate = machine.feedrate.effective()?;
                    let layer_index = if layers.explicit_markers {
                        if layers.count == 0 {
                            // Motion before the first marker belongs to a synthetic startup layer.
                            layers.count = 1;
                        }
                        if layers.current_z.is_none() && machine.known[2] {
                            layers.current_z = Some(target[2]);
                        }
                        layers.count - 1
                    } else if is_known && has_axis {
                        layers.index_for(target[2], extruded && has_axis)?
                    } else {
                        layers.printed_z.len().saturating_sub(1)
                    };
                    if !has_axis {
                        machine.position = target;
                        return Ok(());
                    }
                    // Arc: approximate with chords in the XY plane.
                    let points: Cow<'_, [[f64; 3]]> = if is_arc {
                        if machine.plane != Plane::Xy {
                            return Err(invalid(
                                "GCODE_UNSUPPORTED_COMMAND",
                                "Arcs are only supported in the XY plane (G17)",
                            ));
                        }
                        if !was_known {
                            return Err(invalid(
                                "GCODE_UNSUPPORTED_COMMAND",
                                "Arcs require a known start position",
                            ));
                        }
                        Cow::Owned(arc_points(
                            old_position,
                            target,
                            words.i.map(|v| v * scale),
                            words.j.map(|v| v * scale),
                            words.r.map(|v| v * scale),
                            canonical == G(3),
                        )?)
                    } else {
                        Cow::Borrowed(std::slice::from_ref(&target))
                    };
                    if is_known && points.len() > MAX_MOVES - result.moves.len() {
                        return Err(invalid(
                            "GCODE_MOVE_LIMIT",
                            "G-code exceeded 100000 preview moves",
                        ));
                    }
                    let mut previous = old_position;
                    for &point in points.iter() {
                        let distance = if was_known {
                            (point[0] - previous[0])
                                .hypot(point[1] - previous[1])
                                .hypot(point[2] - previous[2])
                        } else {
                            0.0
                        };
                        if is_known {
                            if extruded {
                                result.print_distance_mm += distance;
                            } else {
                                result.travel_distance_mm += distance;
                            }
                            if let Some(feedrate) = feedrate {
                                result.estimated_time_s += distance / feedrate;
                            }
                            if let Some(bounds) = &mut result.bounds {
                                for (axis, value) in point.iter().enumerate() {
                                    bounds.min[axis] = bounds.min[axis].min(*value);
                                    bounds.max[axis] = bounds.max[axis].max(*value);
                                }
                            } else {
                                result.bounds = Some(GcodeBounds {
                                    min: point,
                                    max: point,
                                });
                            }
                            result.moves.push(GcodeMove {
                                x: point[0],
                                y: point[1],
                                z: point[2],
                                e: machine.extrusion.total_mm,
                                feedrate_mm_s: feedrate.unwrap_or(0.0),
                                layer_index,
                                extruded,
                            });
                        }
                        previous = point;
                    }
                    machine.position = target;
                }
                _ => {}
            }
            Ok(())
        })();
        line_result.map_err(|error| {
            invalid(
                error.code,
                &format!("Line {}: {}", line_index + 1, error.message),
            )
        })?;
    }
    result.layers = if layers.explicit_markers {
        layers.count
    } else {
        layers.printed_z.len()
    };
    if result.moves.is_empty() && result.layers == 0 {
        return Err(invalid(
            "GCODE_EMPTY_PLAN",
            "No movements with a fully known position were found",
        ));
    }
    result.extrusion_mm = machine.extrusion.total_mm;
    result.deposited_volume_mm3 = machine.extrusion.volume_mm3;
    if ![
        result.extrusion_mm,
        result.deposited_volume_mm3,
        result.travel_distance_mm,
        result.print_distance_mm,
        result.estimated_time_s,
    ]
    .iter()
    .all(|v| v.is_finite())
    {
        return Err(invalid("GCODE_NUMERIC", "Totals exceed numeric precision"));
    }
    Ok(result)
}

fn arc_points(
    start: [f64; 3],
    end: [f64; 3],
    i: Option<f64>,
    j: Option<f64>,
    r: Option<f64>,
    counter_clockwise: bool,
) -> Result<Vec<[f64; 3]>> {
    let (cx, cy) = if i.is_some() || j.is_some() {
        (start[0] + i.unwrap_or(0.0), start[1] + j.unwrap_or(0.0))
    } else if let Some(r) = r {
        let dx = end[0] - start[0];
        let dy = end[1] - start[1];
        let d = dx.hypot(dy);
        if d == 0.0 || !r.is_finite() || r.abs() * 2.0 < d - 1e-9 {
            return Err(invalid(
                "GCODE_INVALID_COORDINATE",
                "Arc radius cannot reach the end point",
            ));
        }
        let h = (r * r - (d / 2.0).powi(2)).max(0.0).sqrt();
        let sign = if counter_clockwise == (r > 0.0) {
            1.0
        } else {
            -1.0
        };
        (
            (start[0] + end[0]) / 2.0 - sign * h * dy / d,
            (start[1] + end[1]) / 2.0 + sign * h * dx / d,
        )
    } else {
        return Err(invalid(
            "GCODE_SYNTAX",
            "Arc needs I/J offsets or an R radius",
        ));
    };
    let radius = (start[0] - cx).hypot(start[1] - cy);
    if !radius.is_finite() || radius == 0.0 {
        return Err(invalid("GCODE_INVALID_COORDINATE", "Arc has zero radius"));
    }
    let a0 = (start[1] - cy).atan2(start[0] - cx);
    let a1 = (end[1] - cy).atan2(end[0] - cx);
    let mut sweep = a1 - a0;
    let full = std::f64::consts::TAU;
    if counter_clockwise {
        if sweep <= 1e-9 {
            sweep += full;
        }
    } else if sweep >= -1e-9 {
        sweep -= full;
    }
    let segments =
        ((radius * sweep.abs() / ARC_SEGMENT_MM).ceil() as usize).clamp(1, MAX_ARC_SEGMENTS);
    let mut points = Vec::with_capacity(segments);
    for step in 1..=segments {
        let t = step as f64 / segments as f64;
        let angle = a0 + sweep * t;
        points.push([
            cx + radius * angle.cos(),
            cy + radius * angle.sin(),
            start[2] + (end[2] - start[2]) * t,
        ]);
    }
    if let Some(last) = points.last_mut() {
        *last = end;
    }
    Ok(points)
}

/// Dispatches by dialect: native preview/job stay strict; everything else is tolerant.
pub fn parse_any(gcode: &str) -> Result<(GcodePreview, DialectInfo)> {
    let info = detect(gcode);
    let first = gcode.lines().next().unwrap_or("").trim();
    let preview = if first == format!("; {}", crate::JOB_DIALECT) {
        crate::parse_job(gcode)?
    } else if first == format!("; {}", crate::DIALECT) {
        crate::parse(gcode)?
    } else {
        parse_foreign(gcode)?
    };
    Ok((preview, info))
}

#[cfg(test)]
mod tests {
    use super::*;

    const PRUSA: &str = "; generated by PrusaSlicer 2.7.0 on 2024-01-01\n\
M107\nM104 S215\nM140 S60\nM190 S60\nM109 S215\nG28 W\nG80\nG1 Z0.2 F720\nG1 Y-3 F1000\nG92 E0\nG1 X60 E9 F1000\nG92 E0\nM221 S95\nG21\nG90\nM83\n\
;LAYER_CHANGE\n;Z:0.2\nG1 Z0.2 F720\nG1 X10 Y10 F7200\nG1 X20 Y10 E0.5 F1200\nG1 X20 Y20 E0.5\n\
;LAYER_CHANGE\n;Z:0.4\nG1 Z0.4 F720\nG1 X10 Y10 F7200\nG1 X20 Y10 E0.5 F1200\nG1 E-0.8 F2100\n\
M107\nM104 S0\nM140 S0\n; filament_diameter = 1.75\n; gcode_flavor = marlin2\n";

    #[test]
    fn detects_prusaslicer_and_settings() {
        let info = detect(PRUSA);
        assert_eq!(info.generator, Generator::PrusaSlicer);
        assert_eq!(info.flavor.as_deref(), Some("marlin2"));
        assert_eq!(info.filament_diameter_mm, Some(1.75));
        assert!(!info.native);
    }

    #[test]
    fn prusa_relative_extrusion_and_layer_markers() {
        let preview = parse_foreign(PRUSA).unwrap();
        assert_eq!(preview.layers, 3, "startup + two marked layers");
        assert!(
            (preview.extrusion_mm - (9.0 + 1.5 * 0.95)).abs() < 1e-9,
            "{}",
            preview.extrusion_mm
        );
        assert!((preview.print_distance_mm - 30.0).abs() < 1e-9);
        assert!(
            preview
                .moves
                .iter()
                .any(|m| m.layer_index == 2 && m.extruded)
        );
        assert!(preview.deposited_volume_mm3 > 0.0);
    }

    #[test]
    fn cura_style_absolute_extrusion_with_layer_colon() {
        let cura = ";FLAVOR:Marlin\n;Generated with Cura_SteamEngine 5.6\nM82\nG28\nG92 E0\n;LAYER_COUNT:2\n;LAYER:0\nG0 X0 Y0 Z0.2 F6000\nG1 X10 Y0 E1 F1200\n;LAYER:1\nG0 Z0.4\nG1 X0 Y0 E2\n";
        let (preview, info) = parse_any(cura).unwrap();
        assert_eq!(info.generator, Generator::Cura);
        assert_eq!(info.flavor.as_deref(), Some("Marlin"));
        assert_eq!(preview.layers, 2);
        assert!((preview.extrusion_mm - 2.0).abs() < 1e-9);
        assert_eq!(preview.moves.last().unwrap().layer_index, 1);
    }

    #[test]
    fn infers_layers_from_z_when_no_markers() {
        let raw = "G90\nM82\nG92 E0\nG1 Z0.2 F600\nG1 X0 Y0\nG1 X10 Y0 E1\nG1 Z0.4\nG1 X0 Y0 E2\nG1 Z0.6\nG1 X10 Y0\n";
        let preview = parse_foreign(raw).unwrap();
        assert_eq!(preview.layers, 2, "travel-only Z levels are not layers");
        assert_eq!(preview.moves.iter().filter(|m| m.extruded).count(), 2);
    }

    #[test]
    fn relative_moves_inches_and_compact_words() {
        let raw = "G20\nG91\nG1Z0.01\nG1X1Y0E0.1F60\nG1X0Y1E0.1\n";
        let preview = parse_foreign(raw).unwrap();
        // First XY move from an unknown start establishes position; second is 25.4 mm.
        assert!(
            (preview.print_distance_mm - 25.4).abs() < 1e-9,
            "{}",
            preview.print_distance_mm
        );
        assert!((preview.extrusion_mm - 2.54 * 2.0).abs() < 1e-9);
    }

    #[test]
    fn arcs_are_chorded_in_xy() {
        let raw = "G90\nG1 X10 Y0 Z0.2 F600\nG2 X-10 Y0 I-10 J0 E1\n";
        let preview = parse_foreign(raw).unwrap();
        let half_circle = std::f64::consts::PI * 10.0;
        assert!(
            (preview.print_distance_mm - half_circle).abs() < 0.2,
            "{}",
            preview.print_distance_mm
        );
        assert!(preview.moves.len() > 10);
        let rraw = "G90\nG1 X10 Y0 Z0.2 F600\nG3 X-10 Y0 R10 E1\n";
        let rpreview = parse_foreign(rraw).unwrap();
        assert!((rpreview.print_distance_mm - half_circle).abs() < 0.2);
        assert_eq!(
            parse_foreign("G90\nG18\nG1 X0 Y0 Z0 F600\nG2 X1 Y0 I1 J0\n")
                .unwrap_err()
                .code,
            "GCODE_UNSUPPORTED_COMMAND"
        );
    }

    #[test]
    fn unknown_commands_checksums_and_parentheses_are_skipped() {
        let raw = "N1 G90*45\nN2 M900 K0.2*11\nSET_PRESSURE_ADVANCE ADVANCE=0.04\nM117 Printing\nG1 X0 Y0 Z0.2 F600 (start)\nG01 X5 Y0 E0.1\n";
        let preview = parse_foreign(raw).unwrap();
        assert_eq!(preview.moves.len(), 2);
        assert!((preview.print_distance_mm - 5.0).abs() < 1e-9);
    }

    #[test]
    fn native_dialects_stay_strict_via_parse_any() {
        let bad = format!("; {}\nG1 X0 Y0\n", crate::DIALECT);
        assert_eq!(parse_any(&bad).unwrap_err().code, "GCODE_PROLOGUE");
        let info = detect(&bad);
        assert!(info.native);
        assert_eq!(info.generator, Generator::OpenScadViewer);
    }

    #[test]
    fn empty_or_malformed_motion_fails() {
        assert_eq!(
            parse_foreign("; nothing\nM117 hi\n").unwrap_err().code,
            "GCODE_EMPTY_PLAN"
        );
        assert_eq!(
            parse_foreign("G1 Xabc\n").unwrap_err().code,
            "GCODE_INVALID_NUMBER"
        );
        assert_eq!(
            parse_foreign("G1 X1000001 Y0 Z0\n").unwrap_err().code,
            "GCODE_INVALID_COORDINATE"
        );
    }

    #[test]
    fn explicit_diameter_overrides_header() {
        let raw = "; filament_diameter = 2.85\nG90\nG1 X0 Y0 Z0.2 F600\nG1 X10 Y0 E1\n";
        let header = parse_foreign(raw).unwrap();
        let explicit = parse_foreign_with(raw, Some(1.75)).unwrap();
        assert!(header.deposited_volume_mm3 > explicit.deposited_volume_mm3);
    }

    #[test]
    fn fixed_motion_words_match_ordered_reference() {
        for shift in 0..26 {
            let mut tokens = Vec::new();
            for round in 0..4 {
                for index in 0..26 {
                    let axis = b'A' + ((index + shift) % 26) as u8;
                    let axis = if round % 2 == 0 { axis } else { axis.to_ascii_lowercase() };
                    tokens.push(format!("{}{:.3}", axis as char, (round * 26 + index) as f64 / 8.0));
                }
            }
            let reference = axis_words(tokens.iter().map(String::as_str)).unwrap();
            let actual = MotionWords::parse(tokens.iter().map(String::as_str)).unwrap();
            for (axis, value) in b"XYZEFIJR".iter().zip([
                actual.xyz[0], actual.xyz[1], actual.xyz[2], actual.e,
                actual.f, actual.i, actual.j, actual.r,
            ]) {
                assert_eq!(value, word(&reference, *axis));
            }
        }
        for token in ["X", "Q", "Qbad", "Xbad", "1", "XNaN", "Xinf", "X1e999", "é1"] {
            let tokens = ["X1", token, "X2"];
            assert_eq!(MotionWords::parse(tokens.into_iter()).err(), axis_words(tokens.into_iter()).err());
            assert!(MotionWords::parse(tokens.into_iter()).is_err());
        }
    }
}
