//! Candidate conformance evidence, not production qualification. Expected signs
//! are generated by a separately authored TypeScript bigint rational oracle.
//! This external integration driver uses only the public native predicate API.
use cad_predicates::{
    AuthoredScalar, Decision, InputError, Limits, MAX_WORK, ModelClass, Outcome, PredicateContext,
    Reason, ResidualOutcome, Sign, SourceArena, Stage, ToleranceContext, ToleranceSpec,
    classify_residual, compare_squared_distance, distance_enclosure, orient2d, orient3d,
};
use std::sync::atomic::AtomicBool;
use std::time::{Duration, Instant};

#[derive(Clone, Copy)]
enum SourceLeaf {
    Binary64(u64),
    Rational(i64, u64),
}
#[derive(Clone, Copy)]
enum CandidatePredicate {
    Orient2d,
    Orient3d,
    SquaredDistance,
}
struct CandidateCase {
    id: &'static str,
    predicate: CandidatePredicate,
    dimension: usize,
    leaves: &'static [SourceLeaf],
    expected: i8,
    must_decide: bool,
}
include!("../../../tests/fixtures/predicate-candidate-corpus-v1.rs");

fn authored(values: &[SourceLeaf]) -> Vec<AuthoredScalar> {
    values
        .iter()
        .map(|leaf| match *leaf {
            SourceLeaf::Binary64(bits) => AuthoredScalar::Binary64Bits(bits),
            SourceLeaf::Rational(numerator, denominator) => AuthoredScalar::RationalConstant {
                numerator,
                denominator,
            },
        })
        .collect()
}
fn binary(values: &[f64]) -> Vec<AuthoredScalar> {
    values
        .iter()
        .map(|value| AuthoredScalar::Binary64Bits(value.to_bits()))
        .collect()
}
fn run_case(test: &CandidateCase) -> Decision {
    let arena = SourceArena::authored(test.id, 1, authored(test.leaves)).unwrap();
    let tolerance = ToleranceContext::default_valid();
    let limits = Limits::default();
    let max_work = limits.max_work;
    let mut context = PredicateContext::new(&arena, &tolerance, limits, None);
    let leaves: Vec<_> = (0..test.leaves.len())
        .map(|i| arena.leaf(i).unwrap())
        .collect();
    let result = match test.predicate {
        CandidatePredicate::Orient2d => orient2d(
            &mut context,
            [leaves[0], leaves[1]],
            [leaves[2], leaves[3]],
            [leaves[4], leaves[5]],
        ),
        CandidatePredicate::Orient3d => orient3d(
            &mut context,
            [leaves[0], leaves[1], leaves[2]],
            [leaves[3], leaves[4], leaves[5]],
            [leaves[6], leaves[7], leaves[8]],
            [leaves[9], leaves[10], leaves[11]],
        ),
        CandidatePredicate::SquaredDistance => compare_squared_distance(
            &mut context,
            &leaves[..test.dimension],
            &leaves[test.dimension..test.dimension * 2],
            leaves[test.dimension * 2],
        ),
    }
    .unwrap_or_else(|error| panic!("{}: unexpected input refusal {error:?}", test.id));
    assert_eq!(
        result.context,
        context.identity(),
        "{}: context evidence mismatch",
        test.id
    );
    assert!(
        result.work_used <= max_work,
        "{}: unbounded reported work",
        test.id
    );
    result
}

#[test]
fn native_signs_match_independent_rational_candidate_corpus() {
    let mut decided = 0;
    let mut exact = 0;
    let mut refused = 0;
    for test in CANDIDATE_CORPUS {
        let result = run_case(test);
        match result.outcome {
            Outcome::Sign(sign) => {
                let actual = match sign {
                    Sign::Negative => -1,
                    Sign::Zero => 0,
                    Sign::Positive => 1,
                };
                assert_eq!(
                    actual, test.expected,
                    "{}: incorrect sign via {:?}",
                    test.id, result.stage
                );
                assert_ne!(
                    result.stage,
                    Stage::Admission,
                    "{}: sign without arithmetic evidence",
                    test.id
                );
                decided += 1;
                if result.stage == Stage::ExactExpansion {
                    exact += 1;
                }
            }
            Outcome::Indeterminate(reason) => {
                assert!(
                    !test.must_decide,
                    "{}: bounded ordinary case was refused: {reason:?}",
                    test.id
                );
                assert_eq!(
                    reason,
                    Reason::PrecisionExhausted,
                    "{}: unexpected default-budget refusal",
                    test.id
                );
                refused += 1;
            }
        }
    }
    assert!(
        decided > 100,
        "too little executable exact-sign coverage: {decided}"
    );
    assert!(
        exact > 0,
        "the corpus never exercised adaptive exact arithmetic"
    );
    eprintln!(
        "independent candidate corpus: {} cases, {decided} decided, {exact} exact-stage, {refused} explicit exponent refusals",
        CANDIDATE_CORPUS.len()
    );
}

#[test]
fn authentic_leaf_admission_rejects_nonfinite_noncanonical_and_out_of_range_inputs() {
    for bits in [
        f64::INFINITY.to_bits(),
        f64::NEG_INFINITY.to_bits(),
        f64::NAN.to_bits(),
        0x7ff0000000000001,
    ] {
        assert!(matches!(
            SourceArena::authored("nonfinite", 1, vec![AuthoredScalar::Binary64Bits(bits)]),
            Err(InputError::InvalidInput(_))
        ));
    }
    for (numerator, denominator) in [(1, 0), (2, 6), (0, 3)] {
        assert!(matches!(
            SourceArena::authored(
                "noncanonical",
                1,
                vec![AuthoredScalar::RationalConstant {
                    numerator,
                    denominator
                }]
            ),
            Err(InputError::InvalidInput(_))
        ));
    }
    let arena = SourceArena::authored("index", 1, binary(&[0.0, -0.0, f64::MIN_POSITIVE])).unwrap();
    assert!(arena.leaf(2).is_ok());
    assert!(matches!(arena.leaf(3), Err(InputError::InvalidInput(_))));
}

#[test]
fn foreign_arena_references_are_rejected_even_with_equal_source_labels() {
    let arena = SourceArena::authored("same-source-label", 1, binary(&[0.0, 1.0])).unwrap();
    let other = SourceArena::authored("same-source-label", 1, binary(&[0.0, 1.0])).unwrap();
    let tolerance = ToleranceContext::default_valid();
    let mut context = PredicateContext::new(&arena, &tolerance, Limits::default(), None);
    let zero = arena.leaf(0).unwrap();
    let foreign = other.leaf(1).unwrap();
    assert!(matches!(
        orient2d(&mut context, [zero, zero], [foreign, zero], [zero, foreign]),
        Err(InputError::ProvenanceMismatch)
    ));
    let cancelled = AtomicBool::new(true);
    let mut cancelled_context = PredicateContext::new(
        &arena,
        &tolerance,
        Limits {
            max_work: 0,
            ..Limits::default()
        },
        Some(&cancelled),
    );
    assert!(matches!(
        orient2d(
            &mut cancelled_context,
            [zero, zero],
            [foreign, zero],
            [zero, foreign]
        ),
        Err(InputError::ProvenanceMismatch)
    ));
}

#[test]
fn finite_work_precision_cancel_and_deadline_bounds_fail_explicitly() {
    let epsilon = f64::EPSILON;
    let arena = SourceArena::authored(
        "cancellation-budget",
        1,
        binary(&[0.0, 1.0, 1.0 + epsilon, 1.0 - epsilon]),
    )
    .unwrap();
    let tolerance = ToleranceContext::default_valid();
    let [zero, one, up, down] = [0, 1, 2, 3].map(|index| arena.leaf(index).unwrap());
    let call = |context: &mut PredicateContext<'_>| {
        orient2d(context, [zero, zero], [up, one], [one, down]).unwrap()
    };
    let mut no_work = PredicateContext::new(
        &arena,
        &tolerance,
        Limits {
            max_work: 0,
            ..Limits::default()
        },
        None,
    );
    assert_eq!(
        call(&mut no_work).outcome,
        Outcome::Indeterminate(Reason::ResourceLimit)
    );
    for max_work in [MAX_WORK + 1, u64::MAX] {
        let mut oversized = PredicateContext::new(
            &arena,
            &tolerance,
            Limits {
                max_work,
                ..Limits::default()
            },
            None,
        );
        let decision = call(&mut oversized);
        assert_eq!(
            decision.outcome,
            Outcome::Indeterminate(Reason::ResourceLimit)
        );
        assert_eq!(decision.work_used, 0);
    }
    let mut no_precision = PredicateContext::new(
        &arena,
        &tolerance,
        Limits {
            max_expansion_terms: 0,
            ..Limits::default()
        },
        None,
    );
    assert_eq!(
        call(&mut no_precision).outcome,
        Outcome::Indeterminate(Reason::ResourceLimit)
    );
    let cancelled = AtomicBool::new(true);
    let mut cancel_context =
        PredicateContext::new(&arena, &tolerance, Limits::default(), Some(&cancelled));
    assert_eq!(
        call(&mut cancel_context).outcome,
        Outcome::Indeterminate(Reason::Cancelled)
    );
    let mut oversized_cancel = PredicateContext::new(
        &arena,
        &tolerance,
        Limits {
            max_work: u64::MAX,
            ..Limits::default()
        },
        Some(&cancelled),
    );
    assert_eq!(
        call(&mut oversized_cancel).outcome,
        Outcome::Indeterminate(Reason::Cancelled)
    );
    let mut expired = PredicateContext::new(
        &arena,
        &tolerance,
        Limits {
            deadline: Some(Instant::now() - Duration::from_secs(1)),
            ..Limits::default()
        },
        None,
    );
    assert_eq!(
        call(&mut expired).outcome,
        Outcome::Indeterminate(Reason::DeadlineExceeded)
    );
    let mut oversized_expired = PredicateContext::new(
        &arena,
        &tolerance,
        Limits {
            max_work: u64::MAX,
            deadline: Some(Instant::now() - Duration::from_secs(1)),
            ..Limits::default()
        },
        None,
    );
    assert_eq!(
        call(&mut oversized_expired).outcome,
        Outcome::Indeterminate(Reason::DeadlineExceeded)
    );
}

#[test]
fn distance_rejects_wrong_dimensions_and_negative_radius_without_coercion() {
    let arena = SourceArena::authored("distance-input", 1, binary(&[0.0, 1.0, -1.0])).unwrap();
    let tolerance = ToleranceContext::default_valid();
    let mut context = PredicateContext::new(&arena, &tolerance, Limits::default(), None);
    let [zero, one, negative] = [0, 1, 2].map(|index| arena.leaf(index).unwrap());
    for (p, q) in [
        (vec![zero], vec![one]),
        (vec![zero, zero], vec![one, one, one]),
        (vec![], vec![]),
    ] {
        assert!(matches!(
            compare_squared_distance(&mut context, &p, &q, one),
            Err(InputError::InvalidInput(_))
        ));
    }
    assert!(matches!(
        compare_squared_distance(&mut context, &[zero, zero], &[one, zero], negative),
        Err(InputError::InvalidInput(_))
    ));
}

fn valid_spec() -> ToleranceSpec {
    ToleranceSpec {
        linear_abs: 1e-7,
        linear_rel: 1e-12,
        on_tol: 1e-7,
        clear_tol: 1e-6,
        angular: 1e-8,
        param_floor: 1e-12,
        ulp_guard: 8,
        max_entity_error: 1e-5,
        policy: "candidate-test".into(),
    }
}

#[test]
fn context_identity_tracks_source_revision_bits_and_tolerance_policy() {
    let arena = SourceArena::authored("identity-source", 1, binary(&[0.0, 1.0])).unwrap();
    let changed_bits = SourceArena::authored("identity-source", 1, binary(&[0.0, 2.0])).unwrap();
    let changed_revision =
        SourceArena::authored("identity-source", 2, binary(&[0.0, 1.0])).unwrap();
    let tolerance = ToleranceContext::new(valid_spec()).unwrap();
    let base = PredicateContext::new(&arena, &tolerance, Limits::default(), None).identity();
    assert_ne!(
        base,
        PredicateContext::new(&changed_bits, &tolerance, Limits::default(), None).identity()
    );
    assert_ne!(
        base,
        PredicateContext::new(&changed_revision, &tolerance, Limits::default(), None).identity()
    );
    let mut spec = valid_spec();
    spec.policy = "different-policy".into();
    let changed_policy = ToleranceContext::new(spec).unwrap();
    assert_ne!(
        base,
        PredicateContext::new(&arena, &changed_policy, Limits::default(), None).identity()
    );
    let mut spec = valid_spec();
    spec.linear_rel *= 2.0;
    let changed_bound = ToleranceContext::new(spec).unwrap();
    assert_ne!(
        base,
        PredicateContext::new(&arena, &changed_bound, Limits::default(), None).identity()
    );
}

#[test]
fn invalid_tolerance_profiles_do_not_create_contexts() {
    let mut examples = Vec::new();
    let mut spec = valid_spec();
    spec.on_tol = 0.0;
    examples.push(spec);
    let mut spec = valid_spec();
    spec.clear_tol = spec.on_tol;
    examples.push(spec);
    let mut spec = valid_spec();
    spec.clear_tol = f64::INFINITY;
    examples.push(spec);
    let mut spec = valid_spec();
    spec.linear_rel = f64::NAN;
    examples.push(spec);
    let mut spec = valid_spec();
    spec.max_entity_error = spec.linear_abs / 2.0;
    examples.push(spec);
    for spec in examples {
        assert!(matches!(
            ToleranceContext::new(spec),
            Err(InputError::InvalidInput(_))
        ));
    }
}

#[test]
fn model_classification_uses_proven_enclosures_and_keeps_thresholds_indeterminate() {
    let tolerance = ToleranceContext::new(valid_spec()).unwrap();
    for (distance, expected) in [
        (0.0, 0),
        (5e-8, 0),
        (1e-7, 2),
        (5e-7, 2),
        (1e-6, 2),
        (2e-6, 1),
    ] {
        let arena =
            SourceArena::authored("classifier-distance", 1, binary(&[0.0, distance])).unwrap();
        let mut context = PredicateContext::new(&arena, &tolerance, Limits::default(), None);
        let [zero, other] = [0, 1].map(|index| arena.leaf(index).unwrap());
        let residual =
            match distance_enclosure(&mut context, &[zero, zero], &[other, zero]).unwrap() {
                ResidualOutcome::Proven(value) => value,
                ResidualOutcome::Indeterminate(reason) => {
                    panic!("ordinary residual {distance} unexpectedly refused: {reason:?}")
                }
            };
        let classification = classify_residual(&mut context, Some(&residual)).unwrap();
        match expected {
            0 => assert_eq!(
                classification,
                ModelClass::Coincident,
                "distance={distance}"
            ),
            1 => assert_eq!(classification, ModelClass::Separate, "distance={distance}"),
            _ => assert!(
                matches!(classification, ModelClass::Indeterminate(_)),
                "boundary/gray distance={distance}: {classification:?}"
            ),
        }
    }
}

#[test]
fn missing_or_foreign_residual_evidence_never_becomes_a_model_decision() {
    let arena = SourceArena::authored("residual-owner", 1, binary(&[0.0])).unwrap();
    let tolerance = ToleranceContext::new(valid_spec()).unwrap();
    let mut context = PredicateContext::new(&arena, &tolerance, Limits::default(), None);
    assert_eq!(
        classify_residual(&mut context, None).unwrap(),
        ModelClass::Indeterminate(Reason::MissingProof)
    );
    let zero = arena.leaf(0).unwrap();
    let residual = match distance_enclosure(&mut context, &[zero, zero], &[zero, zero]).unwrap() {
        ResidualOutcome::Proven(value) => value,
        ResidualOutcome::Indeterminate(reason) => {
            panic!("zero distance unexpectedly refused: {reason:?}")
        }
    };
    let other_tolerance = ToleranceContext::new(valid_spec()).unwrap();
    let mut foreign_context =
        PredicateContext::new(&arena, &other_tolerance, Limits::default(), None);
    assert!(matches!(
        classify_residual(&mut foreign_context, Some(&residual)),
        Err(InputError::ContextMismatch)
    ));
    // Resource exhaustion after a proof was issued must not be reset by calling
    // the classifier; the proof is geometric evidence, not a fresh work lease.
    let mut exhausted = PredicateContext::new(
        &arena,
        &tolerance,
        Limits {
            max_work: 0,
            ..Limits::default()
        },
        None,
    );
    assert_eq!(
        classify_residual(&mut exhausted, Some(&residual)).unwrap(),
        ModelClass::Indeterminate(Reason::ResourceLimit)
    );
}

#[test]
fn residual_evidence_that_exceeds_the_entity_error_cap_is_refused() {
    let arena = SourceArena::authored("wide-residual", 1, binary(&[0.0, 1e12, f64::MAX])).unwrap();
    let tolerance = ToleranceContext::new(valid_spec()).unwrap();
    let mut context = PredicateContext::new(&arena, &tolerance, Limits::default(), None);
    let zero = arena.leaf(0).unwrap();
    for index in [1, 2] {
        let other = arena.leaf(index).unwrap();
        assert!(matches!(
            distance_enclosure(&mut context, &[zero, zero], &[other, zero]).unwrap(),
            ResidualOutcome::Indeterminate(Reason::PrecisionExhausted)
        ));
    }
    assert_eq!(
        classify_residual(&mut context, None).unwrap(),
        ModelClass::Indeterminate(Reason::MissingProof)
    );
}
