from decimal import Decimal,localcontext
from pathlib import Path
import math,struct

def d(v):
 bits=struct.unpack('<Q',struct.pack('<d',float(v)))[0]
 return f'D64(0x{bits&0xffffffff:08x}u,0x{bits>>32:08x}u)'
with localcontext() as ctx:
 ctx.prec=460
 def atan(x):
  x=Decimal(x); term=x; total=x; k=1
  while abs(term)>Decimal('1e-455'):
   term *= -x*x
   total += term/Decimal(2*k+1); k+=1
  return total
 pi=16*atan(Decimal(1)/5)-4*atan(Decimal(1)/239)
 fixed=int(2/pi*Decimal(2)**1280)
 limbs=[(fixed>>(16*i))&65535 for i in range(80)]
 ln2=Decimal(2).ln(); high=struct.unpack('<d',struct.pack('<Q',0x3fe62e42fee00000))[0]
 constants='\n'.join(f'const {name}: D64 = {d(value)};' for name,value in [('D64_ONE',1),('D64_HALF',.5),('D64_TWO',2),('D64_LN2',ln2),('D64_LN2_HI',high),('D64_LN2_LO',ln2-Decimal(high)),('D64_PIO2',pi/2),('D64_PIO2_LO',pi/2-Decimal(float(pi/2))),('D64_SQRT2',Decimal(2).sqrt())])
 constants+='\nconst D64_TWO_OVER_PI: array<u32,80> = array<u32,80>('+','.join(f'{v}u' for v in limbs)+');\n'
 def poly(name, coeffs):
  return f'fn {name}(x:D64)->D64 {{\n var value={d(coeffs[-1])};\n'+''.join(f' value=d64_add({d(c)},d64_mul(x,value));\n' for c in reversed(coeffs[:-1]))+' return value;\n}\n'
 constants+=poly('d64_exp_poly',[Decimal(1)/math.factorial(i) for i in range(21)])
 constants+=poly('d64_log_poly',[Decimal(1)/Decimal(2*i+1) for i in range(14)])
 constants+=poly('d64_sin_poly',[Decimal((-1)**i)/math.factorial(2*i+1) for i in range(10)])
 constants+=poly('d64_cos_poly',[Decimal((-1)**i)/math.factorial(2*i) for i in range(11)])
(Path(__file__).resolve().parents[1] / 'src/binary64/constants.wgsl').write_text('// Constants generated by tools/generate-binary64-constants.py; integer words only.\n'+constants)
