#!/usr/bin/env python3
"""Apply GPU integration to an already migrated ISOLATED Curvex checkout.

This is additive to ../prepare.py, never a mutation of the original reference.
"""
from pathlib import Path
import argparse


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise RuntimeError(f"expected one integration anchor: {old[:80]!r}")
    return text.replace(old, new, 1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("destination", type=Path)
    args = parser.parse_args()
    dst = args.destination.resolve()
    own = Path(__file__).resolve().parent
    original = own.parents[3] / "curvex"
    if dst == original.resolve() or not (dst / "osv-migration.patch").exists():
        raise SystemExit("requires an isolated checkout generated by Curvex prepare.py")
    cargo = dst / "Cargo.toml"
    text = cargo.read_text()
    if "curvex-metal-renderer" in text:
        raise SystemExit("GPU integration already applied")
    text = replace_once(text, "[dependencies]\n", '[dependencies]\ncurvex-metal-renderer = { path = ' + __import__('json').dumps(str(own)) + ', features = ["egui-integration"] }\n')
    text = replace_once(text, 'rust-version = "1.87"', 'rust-version = "1.92"')
    render = dst / "src/ui/shape_render.rs"
    source = render.read_text()
    start = source.index("fn add_solid_mesh_mm(")
    end = source.index("\n/// Tessellate", start)
    part = source[start:end]
    part = replace_once(part, 'geometry: &osv_geometry::render::tess::VertexBuffers<Pos2, u32>,', 'geometry: &Rc<osv_geometry::render::tess::VertexBuffers<Pos2, u32>>,')
    part = replace_once(part, '    let origin = ct.origin;', '    if osv_try_gpu_solid(painter, geometry, fill_premult, ct) { return; }\n    let origin = ct.origin;')
    source = source[:start] + part + source[end:]
    source += '\ninclude!("osv_gpu_adapter.rs");\n'
    app = dst / "src/app.rs"
    app_source = replace_once(app.read_text(), '    pub fn new(cc: &eframe::CreationContext) -> Self {', '''    pub fn new(cc: &eframe::CreationContext) -> Self {
        if let Some(state) = &cc.wgpu_render_state {
            if std::env::var_os("CURVEX_DISABLE_GPU_CACHE").is_none() {
            curvex_metal_renderer::egui_integration::install(&cc.egui_ctx, &mut state.renderer.write(), &state.device, state.target_format, 1, true);
            }
        }''')
    gradient = dst / "src/ui/osv_gradient_sampling.rs"
    gradient_source = replace_once(gradient.read_text(), '    let vertices = sampled.positions.iter()', '    if osv_try_gpu_gradient(painter, &sampled, ct) { return; }\n    let vertices = sampled.positions.iter()')
    render_cache = dst / "src/ui/osv_render_cache.rs"
    render_cache_source = replace_once(render_cache.read_text(), 'const OSV_RENDER_CACHE_BYTES: usize = 64 * 1024 * 1024;', 'const OSV_RENDER_CACHE_BYTES: usize = 128 * 1024 * 1024;')
    # All structural checks above precede mutations.
    cargo.write_text(text)
    render.write_text(source)
    (render.parent / "osv_gpu_adapter.rs").write_text((own / "curvex_adapter.rs").read_text())
    app.write_text(app_source)
    gradient.write_text(gradient_source)
    render_cache.write_text(render_cache_source)


if __name__ == "__main__":
    main()
