import {bodyPoints,type DirectBody} from './directModeling'
import {bounds} from './cadWorkbench'
import {solidTopology} from './directSolidTools'
type Line=[number,number,number,number]
export function cadDrawing(bodies:DirectBody[],sectionZ?:number){
 const bb=bounds(bodies),sizes=bb.max.map((v,k)=>v-bb.min[k]),scale=Math.min(110/Math.max(sizes[0],sizes[2],1),75/Math.max(...sizes,1)),lines:Line[]=[],texts:{x:number;y:number;text:string}[]=[]
 const views=[{axes:[0,1],x:20,y:105,name:'TOP XY'},{axes:[0,2],x:160,y:105,name:'FRONT XZ'},{axes:[1,2],x:20,y:195,name:'RIGHT YZ'}]
 for(const view of views){const [u,v]=view.axes,project=(p:number[])=>[view.x+(p[u]-bb.min[u])*scale,view.y-(p[v]-bb.min[v])*scale];texts.push({x:view.x,y:view.y+12,text:view.name});for(const body of bodies){const p=bodyPoints(body);for(const edge of solidTopology(body.mesh).edges){const a=project(p[edge.a]),b=project(p[edge.b]);lines.push([a[0],a[1],b[0],b[1]])}}
 const w=sizes[u]*scale,h=sizes[v]*scale;lines.push([view.x,view.y+5,view.x+w,view.y+5],[view.x-5,view.y,view.x-5,view.y-h]);texts.push({x:view.x+w/2,y:view.y+4,text:sizes[u].toFixed(2)+' mm'},{x:view.x-15,y:view.y-h/2,text:sizes[v].toFixed(2)+' mm'})}
 if(sectionZ!==undefined){if(!Number.isFinite(sectionZ))throw Error('Section height must be finite.');texts.push({x:160,y:207,text:'SECTION Z='+sectionZ.toFixed(2)+' mm'});for(const body of bodies){const p=bodyPoints(body);for(let t=0;t<body.mesh.indices.length;t+=3){const triangle=body.mesh.indices.slice(t,t+3).map(i=>p[i]),hits:number[][]=[];for(let i=0;i<3;i++){const a=triangle[i],b=triangle[(i+1)%3];if((a[2]<sectionZ)!==(b[2]<sectionZ)){const f=(sectionZ-a[2])/(b[2]-a[2]);hits.push(a.map((v,k)=>v+(b[k]-v)*f))}}if(hits.length===2)lines.push([160+(hits[0][0]-bb.min[0])*scale,195-(hits[0][1]-bb.min[1])*scale,160+(hits[1][0]-bb.min[0])*scale,195-(hits[1][1]-bb.min[1])*scale])}}}
 texts.push({x:10,y:10,text:'ORTHOGRAPHIC DRAWING - ALL EDGES VISIBLE - mm'},{x:10,y:16,text:'Scale '+scale.toFixed(4)+':1'});
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="297mm" height="220mm" viewBox="0 0 297 220"><rect width="297" height="220" fill="white"/><g fill="none" stroke="black" stroke-width=".2">${lines.map(l=>`<path d="M${l[0]},${l[1]} L${l[2]},${l[3]}"/>`).join('')}</g><g font-family="sans-serif" font-size="3">${texts.map(t=>`<text x="${t.x}" y="${t.y}">${t.text}</text>`).join('')}</g></svg>`
 const factor=72/25.4,content=['0.5 w',...lines.map(l=>`${l[0]*factor} ${(220-l[1])*factor} m ${l[2]*factor} ${(220-l[3])*factor} l S`),...texts.map(t=>`BT /F1 8 Tf ${t.x*factor} ${(220-t.y)*factor} Td (${t.text.replace(/[()\\]/g,'\\$&')}) Tj ET`)].join('\n')
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>',`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${297*factor} ${220*factor}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${content.length} >>\nstream\n${content}\nendstream`];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return {svg,pdf}
}
export function downloadCad(text:string,type:string,name:string){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
