import { describe, expect, it } from 'vitest'
import {
  emitPolygonMeshGcode,
  emitPolygonMeshGcodeJob,
  inspectGcode,
  planPolygonMeshToolpaths,
  parseGcodePreview,
  sectionPolygonMesh,
  type PolygonMesh,
} from '../src/services/geometry/polygon'

function boxMesh(): PolygonMesh {
  // Unit cube [0,10]^3 as independent triangles (positions xyz, indices).
  const p = [
    [0, 0, 0],
    [10, 0, 0],
    [10, 10, 0],
    [0, 10, 0],
    [0, 0, 10],
    [10, 0, 10],
    [10, 10, 10],
    [0, 10, 10],
  ]
  const faces = [
    [0, 1, 2, 0, 2, 3],
    [4, 6, 5, 4, 7, 6],
    [0, 5, 1, 0, 4, 5],
    [1, 6, 2, 1, 5, 6],
    [2, 7, 3, 2, 6, 7],
    [3, 4, 0, 3, 7, 4],
  ]
  const positions: number[] = []
  const indices: number[] = []
  for (const face of faces) {
    for (let i = 0; i < 6; i += 1) {
      const v = p[face[i]!]!
      const index = positions.length / 3
      positions.push(v[0]!, v[1]!, v[2]!)
      indices.push(index)
    }
  }
  return { positions, indices }
}

describe('mesh section / G-code host API', () => {
  it('sections a box and plans walls through the WASM bridge', () => {
    const mesh = boxMesh()
    const section = sectionPolygonMesh(mesh, 1)
    expect(section.contours.length).toBeGreaterThan(0)
    const plan = planPolygonMeshToolpaths(mesh, 0, 2, {
      layerHeightMm: 0.5,
      wallCount: 1,
    })
    expect(plan.layers.length).toBeGreaterThan(0)
    const gcode = emitPolygonMeshGcode(mesh, 0, 1, {
      layerHeightMm: 0.5,
      wallCount: 1,
    })
    expect(gcode.layerCount).toBeGreaterThan(0)
    expect(gcode.gcode).toContain('G1')
    expect(gcode.dialect).toBe('open-scad-viewer/print-preview 2')
    expect(gcode.preview.layers).toBe(gcode.layerCount)
    expect(parseGcodePreview(gcode.gcode)).toEqual(gcode.preview)
    expect(gcode.preview.depositedVolumeMm3).toBeGreaterThan(0)
    expect(gcode.preview.estimatedTimeS).toBeGreaterThan(0)
    expect(gcode.preview.moves.some(move => move.extruded)).toBe(true)
    expect(gcode.preview.bounds).not.toBeNull()
  })

  it('uses an indexed half-open layer schedule with no extra floating-point layer', () => {
    const result = emitPolygonMeshGcode(boxMesh(), 0, 2, { layerHeightMm: 0.2 })
    expect(result.layerCount).toBe(10)
    expect(result.preview.bounds!.max[2]).toBe(1.8)
    expect([...new Set(result.preview.moves.map(move => move.layerIndex))]).toEqual(Array.from({ length: 10 }, (_, i) => i))
  })

  it('rejects malformed settings and empty export rather than returning a plausible file', () => {
    for (const settings of [{ wallCount: 1.5 }, { wallCount: -1 }, { layerHeightMm: 0 }, { feedrateMmS: 'fast' }, { lineWidthMm: null }, { filamentDiameterMm: 1e-300 }]) {
      expect(() => emitPolygonMeshGcode(boxMesh(), 0, 1, settings as never)).toThrow()
    }
    expect(() => emitPolygonMeshGcode(boxMesh(), 20, 21)).toThrow(/No toolpaths/)
    expect(() => planPolygonMeshToolpaths(boxMesh(), 20, 21, { layerHeightMm: 1e-300 })).toThrow()
  })

  it('does not let untyped settings overwrite the requested operation or geometry', () => {
    const settings = { op: 'mesh_section', mesh: {}, zMin: 100, zMax: 100, layerHeightMm: 0.5 }
    expect(emitPolygonMeshGcode(boxMesh(), 0, 1, settings).layerCount).toBe(2)
  })

  it('rejects corrupted or unsupported G-code through the real WASM boundary', () => {
    const result = emitPolygonMeshGcode(boxMesh(), 0, 1)
    for (const suffix of ['G91', 'M83', 'G2 X1 Y1 I1', 'G1 XNaN', 'G1 ☃1']) {
      expect(() => parseGcodePreview(`${result.gcode}\n${suffix}\n`)).toThrow()
    }
  })

  it('emits firmware-specific print jobs that round-trip through the strict job parser', () => {
    const marlin = emitPolygonMeshGcodeJob(boxMesh(), 0, 1, { layerHeightMm: 0.5 })
    expect(marlin.flavor).toBe('marlin')
    expect(marlin.gcode).toContain(';FLAVOR:Marlin')
    expect(marlin.gcode).toContain('M109 S210')
    const klipper = emitPolygonMeshGcodeJob(boxMesh(), 0, 1, { layerHeightMm: 0.5, flavor: 'klipper' })
    expect(klipper.flavor).toBe('klipper')
    expect(klipper.gcode).toContain('TEMPERATURE_WAIT SENSOR=extruder')
    expect(klipper.gcode).not.toContain('M200')
    const rrf = emitPolygonMeshGcodeJob(boxMesh(), 0, 1, { layerHeightMm: 0.5, flavor: 'reprapfirmware' })
    expect(rrf.gcode).toContain('G10 P0 S210')
    for (const job of [marlin, klipper, rrf]) {
      const inspected = inspectGcode(job.gcode)
      expect(inspected.native).toBe(true)
      expect(inspected.dialect).toBe('open-scad-viewer/print-job 1')
      expect(inspected.preview).toEqual(job.preview)
    }
    expect(() => emitPolygonMeshGcodeJob(boxMesh(), 0, 1, { flavor: 'sailfish' as never })).toThrow()
  })

  it('previews foreign slicer G-code tolerantly and reports the detected dialect', () => {
    const prusa = [
      '; generated by PrusaSlicer 2.7.0',
      'M107', 'M104 S215', 'M190 S60', 'M109 S215', 'G28 W', 'G80', 'G21', 'G90', 'M83', 'G92 E0',
      ';LAYER_CHANGE', ';Z:0.2', 'G1 Z0.2 F720', 'G1 X10 Y10 F7200', 'G1 X20 Y10 E0.5 F1200', 'G1 X20 Y20 E0.5',
      ';LAYER_CHANGE', ';Z:0.4', 'G1 Z0.4 F720', 'G1 X10 Y10 F7200', 'G2 X20 Y20 I10 J0 E0.7', 'G1 E-0.8 F2100',
      'M104 S0', '; filament_diameter = 1.75', '; gcode_flavor = marlin2', '',
    ].join('\n')
    const inspected = inspectGcode(prusa)
    expect(inspected.native).toBe(false)
    expect(inspected.generator).toBe('PrusaSlicer')
    expect(inspected.flavor).toBe('marlin2')
    expect(inspected.filamentDiameterMm).toBe(1.75)
    expect(inspected.dialect).toContain('tolerant')
    expect(inspected.preview.layers).toBe(2)
    expect(inspected.preview.extrusionMm).toBeCloseTo(1.7, 9)
    expect(inspected.preview.moves.some(move => move.extruded && move.layerIndex === 1)).toBe(true)
    expect(inspected.preview.moves.filter(move => move.layerIndex === 1 && move.extruded).length).toBeGreaterThan(4)
    expect(parseGcodePreview(prusa)).toEqual(inspected.preview)
    expect(() => inspectGcode('; nothing here\nM117 hello\n')).toThrow(/No movements/)
  })

  it('preserves compact extrusion and full circles through both WASM preview routes', () => {
    const initial = 'G90\nM83\nG1 X10 Y0 Z0.2 F600\n'
    const plain = parseGcodePreview(`${initial}G3 I-10 J0 E1\nG1 X20 Y1 E2\n`)
    const compact = inspectGcode(`${initial}n42g03i-10j0e1*0\nG1X20(a;b)Y1E2*255\n`)
    expect(compact.native).toBe(false)
    expect(compact.preview).toEqual(plain)
    expect(plain.extrusionMm).toBe(3)
    expect(plain.moves.length).toBeGreaterThan(50)
    expect(plain.printDistanceMm).toBeCloseTo(2 * Math.PI * 10 + Math.hypot(10, 1), 0)
    expect(plain.moves.at(-1)).toMatchObject({x: 20, y: 1, z: 0.2, e: 3, extruded: true})
  })

  it('refuses arc expansion past the preview move budget before WASM result serialization', () => {
    const gcode = 'G90\nM83\nG1 X20 Y0 Z0.2 F600\n' + 'G2 X20 Y0 I-20 E0.001\n'.repeat(1563)
    for (const parse of [parseGcodePreview, inspectGcode]) {
      expect(() => parse(gcode)).toThrow(expect.objectContaining({code: 'GCODE_MOVE_LIMIT'}))
    }
  })

  it('accounts for volumetric extrusion, flow and diameter changes through WASM', () => {
    const gcode = 'G90\nM82\nG1 X0 Y0 Z0.2 F600\nM200 T1000 D2 S1\nM221 T1000 S50\nT1000\nG92 E100\nG1 X10 E102\nM200 S0 D4\nG92 E0\nM221 S200\nG1 X20 E1\n'
    const preview = parseGcodePreview(gcode)
    expect(inspectGcode(gcode).preview).toEqual(preview)
    expect(preview.extrusionMm).toBeCloseTo(2 + 1 / Math.PI, 12)
    expect(preview.depositedVolumeMm3).toBeCloseTo(1 + 8 * Math.PI, 12)
    expect(preview.moves.at(-1)?.e).toBe(preview.extrusionMm)
    expect(preview.printDistanceMm).toBe(20)
  })

  it('applies modal feedrate overrides and backup/restore through WASM', () => {
    const gcode = 'G1 X0 Y0 Z0 F600\nM83\nM220S50\nM220 B S200\nG1 X10 E1\nM220 R B\nG1 X20 E1\nM220 R\nG1 X30 E1\nM220 S100\nG1 X40 E1\n'
    const preview = parseGcodePreview(gcode)
    expect(inspectGcode(gcode).preview).toEqual(preview)
    expect(preview.moves.map(move => move.feedrateMmS)).toEqual([10, 20, 5, 20, 10])
    expect(preview.estimatedTimeS).toBe(4)
    expect(preview.extrusionMm).toBe(4)
    for (const command of ['M220 S0', 'M220 S1.5', 'M220 S32768']) {
      expect(() => inspectGcode(`${gcode}${command}\n`)).toThrow(expect.objectContaining({code: 'GCODE_INVALID_FEEDRATE'}))
    }
  })

  it('rejects invalid extrusion modes and excessive tool state through WASM', () => {
    const initial = 'G1 X0 Y0 Z0\n'
    for (const setting of ['M200 S2', 'M221 S-1', 'M200 T-1 D2', 'T1.5']) {
      expect(() => inspectGcode(initial + setting)).toThrow(expect.objectContaining({code: 'GCODE_INVALID_SETTINGS'}))
    }
    const tooMany = initial + Array.from({length: 256}, (_, i) => `T${(i + 1) * 1000}\n`).join('')
    expect(() => inspectGcode(tooMany)).toThrow(expect.objectContaining({code: 'GCODE_TOOL_LIMIT'}))
    expect(inspectGcode(initial + 'M83\nG1 X1 E1\n').preview.extrusionMm).toBe(1)
  })
})
