import {readFileSync} from 'node:fs'
import {describe,expect,it} from 'vitest'
import {compileModelGraphText} from '../src/services/modelGraphText'
import {compileTextRust} from '../src/services/geometryRustKernel'
// Captured from the TypeScript frontend before its replacement, not generated by Rust.
const fixtures=JSON.parse(readFileSync('tests/fixtures/modelgraph-text-compatibility.json','utf8'))
describe('Rust frontend compatibility',()=>{
 for(const fixture of fixtures) it(fixture.path,()=>{
  const result=compileModelGraphText(fixture.source)
  expect(result.document).toEqual(fixture.document)
  expect(result.customizer).toEqual(fixture.customizer)
 })
 it('preserves UTF-16 editor offsets after Unicode comments',()=>{
  const source='// 🧱 коробка\nparam size: -12mm range -20mm..20mm\nshow box([1,2,3])'
  const result=compileTextRust<{customizer:{valueStart:number,valueEnd:number}[]}>(source)
  const {valueStart,valueEnd}=result.customizer[0]!
  expect(source.slice(valueStart,valueEnd)).toBe('-12')
 })
 it('recovers after invalid source without stale compiler state',()=>{
  expect(()=>compileModelGraphText('show sphere(unknown)')).toThrow('Unknown name')
  const first=compileModelGraphText('show sphere(2)')
  compileModelGraphText('show box([3,4,5])')
  expect(compileModelGraphText('show sphere(2)').document).toEqual(first.document)
 })
})
