import {readFileSync} from 'node:fs'
import {describe,expect,it} from 'vitest'
import {compileRushFrontend} from '../src/services/rushFrontend'
import {compileTextRust} from '../src/services/languages/kernel'
// Captured from the TypeScript frontend before its replacement, not generated by Rust.
const fixtures=JSON.parse(readFileSync('tests/fixtures/rush-frontend-compatibility.json','utf8'))
describe('Rust frontend compatibility',()=>{
 for(const fixture of fixtures) it(fixture.path,()=>{
  const result=compileRushFrontend(fixture.source)
  // Rush owns stable part IDs; compare the independent historical graph modulo IDs.
  const normalize = (document: any) => {
   const ids = new Map(document.nodes.map((node: any, i: number) => [node.id, `node${i}`]))
   return JSON.parse(JSON.stringify(document), (_key, value) => typeof value === 'string' && ids.has(value) ? ids.get(value) : value)
  }
  expect(normalize(result.document)).toEqual(normalize(fixture.document))
  expect(result.customizer).toEqual(fixture.customizer)
 })
 it('preserves UTF-16 editor offsets after Unicode comments',()=>{
  const source='// 🧱 коробка\nparam size: -12mm range -20mm..20mm\nshow box([1,2,3])'
  const result=compileTextRust<{customizer:{valueStart:number,valueEnd:number}[]}>(source)
  const {valueStart,valueEnd}=result.customizer[0]!
  expect(source.slice(valueStart,valueEnd)).toBe('-12')
 })
 it('recovers after invalid source without stale compiler state',()=>{
  expect(()=>compileRushFrontend('show sphere(unknown)')).toThrow('Unknown name')
  const first=compileRushFrontend('show sphere(2)')
  compileRushFrontend('show box([3,4,5])')
  expect(compileRushFrontend('show sphere(2)').document).toEqual(first.document)
 })
})
