import { describe, expect, it } from 'vitest'
import { DEEP_MESH_WGSL, EDGE_WGSL, MESH_MATCAP_WGSL, MESH_PBR_WGSL, MESH_SECTION_CAP_WGSL, MESH_TOON_WGSL, MESH_UNLIT_WGSL, MESH_WGSL } from '../src/services/shaders'
import { immediateObjectShader, instancedObjectShader } from '../src/services/shaders/variants'
import { VARIANTS_GOLDEN } from '../src/services/shaders/generated/variants.golden'

// The golden file is generated by the raster-core `wgsl_export` bin from the
// Rust variants module; this test pins the hand-written TypeScript transforms
// to those byte-exact outputs. Regenerate: npm run shaders:export.
// Names match the Rust OBJECT_SHADERS entries (snake_case golden keys).
const OBJECT_SHADERS = [
  ['mesh', MESH_WGSL, 'V'],
  ['mesh_pbr', MESH_PBR_WGSL, 'V'],
  ['mesh_matcap', MESH_MATCAP_WGSL, 'V'],
  ['mesh_toon', MESH_TOON_WGSL, 'V'],
  ['mesh_unlit', MESH_UNLIT_WGSL, 'V'],
  ['mesh_section_cap', MESH_SECTION_CAP_WGSL, 'V'],
  ['deep_mesh', DEEP_MESH_WGSL, 'V'],
  ['edge', EDGE_WGSL, 'EdgeV'],
] as const

describe('variant golden parity (TS vs Rust)', () => {
  it.each(OBJECT_SHADERS.map(([name, code, output]) => [name, code, output] as const))(
    'immediate variant of %s matches the Rust golden', (name, code) => {
      expect(VARIANTS_GOLDEN[`immediate:${name}`]).toBeDefined()
      expect(immediateObjectShader(code)).toBe(VARIANTS_GOLDEN[`immediate:${name}`])
    })

  it.each(OBJECT_SHADERS.map(([name, code, output]) => [name, code, output] as const))(
    'instanced variant of %s matches the Rust golden', (name, code, output) => {
      expect(VARIANTS_GOLDEN[`instanced:${name}`]).toBeDefined()
      expect(instancedObjectShader(code, output)).toBe(VARIANTS_GOLDEN[`instanced:${name}`])
    })

  it('golden covers every object shader and both transforms', () => {
    expect(Object.keys(VARIANTS_GOLDEN).sort()).toEqual(OBJECT_SHADERS
      .flatMap(([name]) => [`immediate:${name}`, `instanced:${name}`])
      .sort())
  })
})
