import {it,expect} from 'vitest'
import {lightenSolid,spatialGraph,type LighteningOptions} from '../src/services/solidLightening'
import {extrudeDirectSketch,directBodiesScad} from '../src/services/directModeling'
import {inspectPolygonMesh} from '../src/services/polygonKernel'
const box=()=>extrudeDirectSketch({id:'s',name:'Box',closed:true,points:[[0,0],[16,0],[16,12],[0,12]]},10,'0')
const o:LighteningOptions={pattern:'spatial',axis:'z',cell:10,rib:3.2,rim:0,bottom:0,top:0,seed:42,jitter:.5,lineWidth:.45,perimeters:3,skin:0,step:1.2,diagonals:true}
it('has edges in all three dimensions and repeatable randomized nodes',()=>{const a=spatialGraph(box(),o),b=spatialGraph(box(),o);expect(a).toEqual(b);expect(a.nodes).not.toEqual(spatialGraph(box(),{...o,seed:43}).nodes);for(let k=0;k<3;k++)expect(a.edges.some(([i,j])=>a.nodes[i][k]!==a.nodes[j][k])).toBe(true)})
it.each(['spatial','bone'] as const)('generates a closed lighter %s volume',(pattern)=>{const b=box(),r=lightenSolid(b,{...o,pattern}),report=inspectPolygonMesh(r.mesh);expect(report.closed).toBe(true);expect(report.signedVolumeMm3).toBeLessThan(1920);expect(report.signedVolumeMm3).toBeGreaterThan(0);expect(r.mesh.indices.length).toBeGreaterThan(100);expect(directBodiesScad({version:1,sketches:[],bodies:[r]}).length).toBeLessThan(250000)},20000)
it('rebuilds dense generated geometry from compact OpenSCAD source',async()=>{const {parseOpenSCAD}=await import('../src/services/openscadParser');const r=lightenSolid(box(),o),source=directBodiesScad({version:1,sketches:[],bodies:[r]});expect(source).toContain('polyhedron');let built;try{built=await parseOpenSCAD(source)}catch(e){throw Error(String(e).split('\n')[0]+' CODE '+source.slice((e as {start:number}).start-70,(e as {start:number}).start+70))}expect(built.meshes).toHaveLength(1)},20000)
it('retains an outer skin and supports opening its top',()=>{const b=box(),closed=lightenSolid(b,{...o,pattern:'bone',skin:2.4,openTop:false}),open=lightenSolid(b,{...o,pattern:'bone',skin:2.4,openTop:true});expect(inspectPolygonMesh(closed.mesh).closed).toBe(true);expect(inspectPolygonMesh(open.mesh).closed).toBe(true);expect(inspectPolygonMesh(open.mesh).signedVolumeMm3).toBeLessThan(inspectPolygonMesh(closed.mesh).signedVolumeMm3)},20000)
it('rejects unresolved ribs and excessive 3D node counts',()=>{expect(()=>lightenSolid(box(),{...o,step:3})).toThrow('step');expect(()=>spatialGraph(box(),{...o,cell:1})).toThrow('125')})
it('restricts lattice to walls with optional solid core',()=>{const walls=lightenSolid(box(),{...o,wallDepth:2.4,keepCore:false}),core=lightenSolid(box(),{...o,wallDepth:2.4,keepCore:true}),full=lightenSolid(box(),o);const v=(b:ReturnType<typeof box>)=>inspectPolygonMesh(b.mesh).signedVolumeMm3;expect(inspectPolygonMesh(walls.mesh).closed).toBe(true);expect(inspectPolygonMesh(core.mesh).closed).toBe(true);expect(v(walls)).toBeLessThan(v(full));expect(v(core)).toBeGreaterThan(v(walls));expect(v(core)).toBeLessThan(1920)},20000)
it('rejects wall layers below sampling resolution',()=>{expect(()=>lightenSolid(box(),{...o,wallDepth:1})).toThrow('Wall depth')})
