[package]
name = "compute-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
wgpu = { version = "30", default-features = false, features = ["metal", "vulkan", "wgsl", "std"] }
gpu-compute = { path = "../gpu-compute" }

[target.'cfg(windows)'.dependencies]
wgpu = { version = "30", default-features = false, features = ["dx12"] }

[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }
