//! Oslo algorithm (discrete B-spline knot refinement) as an alternative
//! one-pass backend to `Curve::refine` (The NURBS Book A5.4).
//!
//! Every new control point is a convex combination `Q_j = Σ_i α_{i,p}(j)·P_i`
//! of the old homogeneous control points, where the α are discrete B-spline
//! coefficients generated by the knot-row recurrence
//! `α_{i,0}(j) = [u_i ≤ t_j < u_{i+1}]`,
//! `α_{i,k}(j) = ((t_{j+k}−u_i)/(u_{i+k}−u_i))·α_{i,k−1}(j)
//!              + ((u_{i+k+1}−t_{j+k})/(u_{i+k+1}−u_{i+1}))·α_{i+1,k−1}(j)`
//! with 0/0 treated as 0. No matrix inversion and no repeated one-step
//! Boehm insertion: the whole refined control net is produced in a single
//! sweep of knot rows. All arithmetic happens in homogeneous space
//! (w·P, w), matching the rest of the crate; positive weights in give
//! positive weights out because each row of α is a partition of unity of
//! nonnegative coefficients.
use crate::{Result, check, input, numeric, resource};
use crate::curve::Curve;

/// Result of an Oslo refinement: the refined curve plus stability evidence.
#[derive(Debug)]
pub struct RefineReport {
    pub curve: Curve,
    /// Number of knots added relative to the original knot vector.
    pub inserted: usize,
    /// Maximum |discrete B-spline coefficient| seen across all knot rows.
    /// Coefficients are theoretically in [0, 1] (nonnegative partition of
    /// unity), so a value materially above 1 would signal instability.
    pub max_coefficient_growth: f64,
}

/// Oslo algorithm: refine `curve` onto the finer knot vector `new_knots`
/// in one pass via discrete B-spline coefficients.
///
/// `new_knots` is the FULL target knot vector: sorted nondecreasing, finite,
/// containing the original knot multiset, with every added value inside the
/// active domain and final multiplicities within the usual limits
/// (degree+1 at the domain boundary, degree in the interior).
/// `max_insertions` caps the number of added knots; the 256-control budget
/// applies to the result. Both are enforced via resource-limit errors.
pub fn refine_oslo(curve: &Curve, new_knots: &[f64], max_insertions: usize) -> Result<RefineReport> {
    curve.validate()?;
    let p = curve.degree;
    let n = curve.control_points.len();
    let u = &curve.knots;
    let [a, b] = curve.domain();
    for (i, &t) in new_knots.iter().enumerate() {
        check(t.is_finite(), "Refined knot vector must be finite")?;
        check(
            i == 0 || new_knots[i - 1] <= t,
            "Refined knot vector must be sorted nondecreasing",
        )?;
    }
    // Multiset containment: the target must contain the original knots.
    // Values not matched against the original vector are the insertions.
    let mut inserted: Vec<f64> = Vec::new();
    let (mut i, mut j) = (0, 0);
    while j < new_knots.len() {
        if i < u.len() && new_knots[j] == u[i] {
            i += 1;
            j += 1;
        } else if i < u.len() && new_knots[j] > u[i] {
            return Err(input(
                "Refined knot vector must contain the original knot multiset",
            ));
        } else {
            inserted.push(new_knots[j]);
            j += 1;
        }
    }
    check(
        i == u.len(),
        "Refined knot vector must contain the original knot multiset",
    )?;
    for &t in &inserted {
        check(
            t >= a && t <= b,
            "Refinement knots must lie inside the active domain",
        )?;
    }
    // Final multiplicity limits mirror `Curve::refine`: degree+1 at the
    // domain boundary, degree in the interior.
    let mut g = 0;
    while g < new_knots.len() {
        let mut end = g + 1;
        while end < new_knots.len() && new_knots[end] == new_knots[g] {
            end += 1;
        }
        let v = new_knots[g];
        let max = if v <= a || v >= b { p + 1 } else { p };
        check(
            end - g <= max,
            "Refinement would exceed the permitted knot multiplicity",
        )?;
        g = end;
    }
    let out_controls = new_knots.len().saturating_sub(p + 1);
    if out_controls > 256 || out_controls == 0 {
        return Err(resource("The result exceeds 256 control points"));
    }
    if inserted.len() > max_insertions {
        return Err(resource("Refinement exceeds the insertion budget"));
    }

    // Homogeneous control net (w·P, w).
    let dim = curve.control_points[0].len();
    let h: Vec<Vec<f64>> = curve
        .control_points
        .iter()
        .zip(&curve.weights)
        .map(|(point, weight)| {
            point
                .iter()
                .map(|x| x * weight)
                .chain(std::iter::once(*weight))
                .collect()
        })
        .collect();

    let mut out = vec![vec![0.; dim + 1]; out_controls];
    let mut max_coefficient_growth = 0_f64;
    for row in 0..out_controls {
        let t0 = new_knots[row];
        // Span mu with u[mu] <= t0 < u[mu+1]. At the domain end the
        // half-open interval is empty; fall back to the last span, the
        // same left-continuous convention `find_span` uses for u == b.
        let mut mu = u.partition_point(|&x| x <= t0);
        mu = mu.saturating_sub(1).min(n - 1);
        // alpha rows: alpha_{i,0}(row) then the recurrence up to order p.
        // Index n stays zero so the i+1 read at i == n-1 is a true zero.
        let mut prev = vec![0.; n + 1];
        prev[mu] = 1.;
        for k in 1..=p {
            let t = new_knots[row + k];
            let mut next = vec![0.; n + 1];
            let lo = mu.saturating_sub(k);
            for i in lo..=mu {
                let left = u[i + k] - u[i];
                if left > 0. {
                    next[i] += (t - u[i]) / left * prev[i];
                }
                let right = u[i + k + 1] - u[i + 1];
                if right > 0. {
                    next[i] += (u[i + k + 1] - t) / right * prev[i + 1];
                }
            }
            prev = next;
        }
        let lo = mu.saturating_sub(p);
        for i in lo..=mu {
            let alpha = prev[i];
            max_coefficient_growth = max_coefficient_growth.max(alpha.abs());
            if alpha == 0. {
                continue;
            }
            for axis in 0..=dim {
                out[row][axis] += alpha * h[i][axis];
            }
        }
    }

    let weights: Vec<f64> = out.iter().map(|q| q[dim]).collect();
    numeric(
        weights.iter().all(|w| w.is_finite() && *w > 0.),
        "Oslo refinement lost positive finite weights",
    )?;
    let control_points = out
        .iter()
        .zip(&weights)
        .map(|(q, w)| q[..dim].iter().map(|x| x / w).collect())
        .collect();
    let refined = Curve {
        degree: p,
        knots: new_knots.to_vec(),
        control_points,
        weights,
        periodic: false,
    };
    refined.validate()?;
    numeric(
        max_coefficient_growth.is_finite(),
        "Oslo coefficients exhausted finite precision",
    )?;
    Ok(RefineReport {
        curve: refined,
        inserted: inserted.len(),
        max_coefficient_growth,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Deterministic splitmix64 stream; no external RNG dependency.
    struct Rng(u64);
    impl Rng {
        fn next(&mut self) -> u64 {
            self.0 = self.0.wrapping_add(0x9E3779B97F4A7C15);
            let mut z = self.0;
            z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
            z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
            z ^ (z >> 31)
        }
        fn f64(&mut self) -> f64 {
            (self.next() >> 11) as f64 / (1u64 << 53) as f64
        }
        fn range(&mut self, lo: f64, hi: f64) -> f64 {
            lo + (hi - lo) * self.f64()
        }
    }

    /// Random clamped curve on [0, 1] with the given interior knots.
    fn random_curve(rng: &mut Rng, degree: usize, interior: &[f64], dim: usize) -> Curve {
        let mut knots = vec![0.; degree + 1];
        knots.extend_from_slice(interior);
        knots.extend(std::iter::repeat_n(1., degree + 1));
        let count = knots.len() - degree - 1;
        let control_points = (0..count)
            .map(|_| (0..dim).map(|_| rng.range(-5., 5.)).collect())
            .collect();
        let weights = (0..count).map(|_| rng.range(0.5, 2.)).collect();
        let curve = Curve {
            degree,
            knots,
            control_points,
            weights,
            periodic: false,
        };
        curve.validate().unwrap();
        curve
    }

    fn random_interior(rng: &mut Rng, count: usize) -> Vec<f64> {
        // Distinct, sorted, multiplicity 1 interior knots away from 0/1.
        let mut interior: Vec<f64> = (0..count)
            .map(|i| (i as f64 + 0.25 + 0.5 * rng.f64()) / count as f64)
            .collect();
        interior.sort_by(f64::total_cmp);
        interior
    }

    /// Merge the original knot vector with inserted values into the full
    /// target vector consumed by `refine_oslo`.
    fn target_knots(curve: &Curve, inserted: &[f64]) -> Vec<f64> {
        let mut knots = curve.knots.clone();
        knots.extend_from_slice(inserted);
        knots.sort_by(f64::total_cmp);
        knots
    }

    fn max_deviation(first: &Curve, second: &Curve) -> f64 {
        let [a, b] = first.domain();
        let mut max = 0_f64;
        for i in 0..=256 {
            let u = a + (b - a) * i as f64 / 256.;
            let pa = first.evaluate(u).unwrap().point;
            let pb = second.evaluate(u).unwrap().point;
            let d = pa
                .iter()
                .zip(&pb)
                .map(|(x, y)| (x - y) * (x - y))
                .sum::<f64>()
                .sqrt();
            max = max.max(d);
        }
        max
    }

    #[test]
    fn oslo_matches_boehm_refine_on_random_curves() {
        let mut rng = Rng(0x0510_5EED ^ 0xDEAD_BEEF);
        for case in 0..12 {
            let degree = 1 + (rng.next() % 4) as usize;
            let dim = if case % 2 == 0 { 2 } else { 3 };
            let interior = random_interior(&mut rng, degree + case % 5);
            let curve = random_curve(&mut rng, degree, &interior, dim);
            // Inserted knots: fresh interior values plus repeats of existing
            // ones (multiplicity increase within the degree limit).
            let mut inserted: Vec<f64> = (0..6).map(|_| rng.range(0.02, 0.98)).collect();
            for &k in &interior {
                if degree >= 2 && rng.f64() < 0.5 {
                    inserted.push(k);
                }
            }
            inserted.sort_by(f64::total_cmp);
            let target = target_knots(&curve, &inserted);
            let report = refine_oslo(&curve, &target, usize::MAX).unwrap();
            let reference = curve.refine(&inserted).unwrap();
            assert_eq!(report.curve.knots, reference.knots, "case {case}");
            assert_eq!(report.inserted, inserted.len(), "case {case}");
            assert!(
                report.max_coefficient_growth > 0.
                    && report.max_coefficient_growth <= 1. + 1e-9,
                "case {case}: growth {}",
                report.max_coefficient_growth
            );
            let deviation = max_deviation(&report.curve, &reference);
            assert!(deviation < 1e-9, "case {case}: deviation {deviation}");
            let against_original = max_deviation(&curve, &report.curve);
            assert!(
                against_original < 1e-9,
                "case {case}: geometry moved {against_original}"
            );
        }
    }

    #[test]
    fn oslo_empty_refinement_is_identity() {
        let mut rng = Rng(7);
        let curve = random_curve(&mut rng, 3, &[0.3, 0.6], 3);
        let report = refine_oslo(&curve, &curve.knots.clone(), 0).unwrap();
        assert_eq!(report.inserted, 0);
        assert_eq!(report.curve.knots, curve.knots);
        // Knot rows are recomputed, so allow rounding-level deviation.
        assert!(max_deviation(&curve, &report.curve) < 1e-12);
    }

    #[test]
    fn oslo_thousand_insertions_hit_the_control_budget() {
        // A cubic starts with >= 4 controls; 1000 insertions push the result
        // past the crate-wide 256-control budget. Both backends must reject
        // with the resource-limit code rather than compute.
        let mut rng = Rng(0x1000);
        let curve = random_curve(&mut rng, 3, &[], 3);
        let inserted: Vec<f64> = (0..1000)
            .map(|i| (i as f64 + 0.5) / 1000.)
            .collect();
        let target = target_knots(&curve, &inserted);
        let error = refine_oslo(&curve, &target, 1000).unwrap_err();
        assert_eq!(error.code, crate::RESOURCE_LIMIT);
        let error = curve.refine(&inserted).unwrap_err();
        assert_eq!(error.code, crate::RESOURCE_LIMIT);
        // Same request, tighter caller budget: still a resource error.
        let small: Vec<f64> = (0..20).map(|i| (i as f64 + 0.5) / 20.).collect();
        let target = target_knots(&curve, &small);
        let error = refine_oslo(&curve, &target, 19).unwrap_err();
        assert_eq!(error.code, crate::RESOURCE_LIMIT);
    }

    #[test]
    fn oslo_stress_max_feasible_insertions_on_cubic() {
        // 250 distinct insertions into a 4-control cubic Bezier: the largest
        // refinement that fits the 256-control budget. Both paths complete.
        let mut rng = Rng(0x57EE55);
        let curve = random_curve(&mut rng, 3, &[], 3);
        let mut inserted: Vec<f64> = (0..250)
            .map(|i| (i as f64 + 0.05 + 0.9 * rng.f64()) / 250.)
            .collect();
        inserted.sort_by(f64::total_cmp);
        let target = target_knots(&curve, &inserted);
        let report = refine_oslo(&curve, &target, 250).unwrap();
        let reference = curve.refine(&inserted).unwrap();
        assert_eq!(report.curve.knots, reference.knots);
        assert_eq!(report.inserted, 250);
        assert_eq!(report.curve.control_points.len(), 254);
        // Discrete B-splines are a nonnegative partition of unity: growth
        // must stay at 1 up to rounding.
        assert!(
            report.max_coefficient_growth <= 1. + 1e-9,
            "growth {}",
            report.max_coefficient_growth
        );
        let deviation = max_deviation(&report.curve, &reference);
        assert!(deviation < 1e-8, "deviation {deviation}");
        let against_original = max_deviation(&curve, &report.curve);
        assert!(against_original < 1e-8, "geometry moved {against_original}");
    }

    #[test]
    fn oslo_refines_periodic_curve() {
        // Closed cubic: 6 unique control points on a hexagon, periodic storage.
        let degree = 3;
        let unique = 6;
        let active: Vec<f64> = (0..=unique).map(|i| i as f64).collect();
        let period = unique as f64;
        let mut knots: Vec<f64> = active[active.len() - 1 - degree..active.len() - 1]
            .iter()
            .map(|v| v - period)
            .collect();
        knots.extend_from_slice(&active);
        knots.extend(active[1..=degree].iter().map(|v| v + period));
        let mut control_points: Vec<Vec<f64>> = (0..unique)
            .map(|i| {
                let angle = std::f64::consts::TAU * i as f64 / unique as f64;
                vec![angle.cos(), angle.sin()]
            })
            .collect();
        let wrapped_points: Vec<Vec<f64>> = control_points[..degree].to_vec();
        control_points.extend(wrapped_points);
        let mut weights = vec![1.; unique];
        let wrapped_weights: Vec<f64> = weights[..degree].to_vec();
        weights.extend(wrapped_weights);
        let curve = Curve {
            degree,
            knots,
            control_points,
            weights,
            periodic: true,
        };
        curve.validate().unwrap();
        let inserted = vec![0.5, 1.5, 2.5, 2.5, 4.25];
        let target = target_knots(&curve, &inserted);
        let report = refine_oslo(&curve, &target, usize::MAX).unwrap();
        let reference = curve.refine(&inserted).unwrap();
        assert_eq!(report.curve.knots, reference.knots);
        assert_eq!(report.inserted, inserted.len());
        let deviation = max_deviation(&report.curve, &reference);
        assert!(deviation < 1e-9, "deviation {deviation}");
        let against_original = max_deviation(&curve, &report.curve);
        assert!(against_original < 1e-9, "geometry moved {against_original}");
    }

    #[test]
    fn oslo_rejects_invalid_inputs() {
        let mut rng = Rng(0xBAD);
        let curve = random_curve(&mut rng, 2, &[0.4, 0.7], 2);
        // Unsorted target vector.
        let mut unsorted = curve.knots.clone();
        unsorted.push(0.5);
        unsorted.push(0.2);
        let error = refine_oslo(&curve, &unsorted, usize::MAX).unwrap_err();
        assert_eq!(error.code, crate::INVALID_INPUT);
        // Inserted knot outside the active domain.
        let outside = target_knots(&curve, &[1.5]);
        let error = refine_oslo(&curve, &outside, usize::MAX).unwrap_err();
        assert_eq!(error.code, crate::INVALID_INPUT);
        // Target vector missing an original interior knot.
        let missing: Vec<f64> = curve
            .knots
            .iter()
            .copied()
            .filter(|&k| k != 0.4)
            .collect();
        let error = refine_oslo(&curve, &missing, usize::MAX).unwrap_err();
        assert_eq!(error.code, crate::INVALID_INPUT);
        // Non-finite target knot.
        let mut nan = curve.knots.clone();
        nan.push(f64::NAN);
        let error = refine_oslo(&curve, &nan, usize::MAX).unwrap_err();
        assert_eq!(error.code, crate::INVALID_INPUT);
        // Insertion budget exceeded.
        let target = target_knots(&curve, &[0.1, 0.2]);
        let error = refine_oslo(&curve, &target, 1).unwrap_err();
        assert_eq!(error.code, crate::RESOURCE_LIMIT);
        // Multiplicity beyond the degree in the interior.
        let target = target_knots(&curve, &[0.4, 0.4]);
        let error = refine_oslo(&curve, &target, usize::MAX).unwrap_err();
        assert_eq!(error.code, crate::INVALID_INPUT);
    }

    #[test]
    fn oslo_increases_multiplicity_of_existing_knots() {
        let mut rng = Rng(0xBEEF01);
        let degree = 3;
        let interior = random_interior(&mut rng, 4);
        let curve = random_curve(&mut rng, degree, &interior, 3);
        // Raise every interior knot to multiplicity 2 and one to 3.
        let mut inserted = interior.clone();
        inserted.push(interior[1]);
        inserted.sort_by(f64::total_cmp);
        let target = target_knots(&curve, &inserted);
        let report = refine_oslo(&curve, &target, usize::MAX).unwrap();
        let reference = curve.refine(&inserted).unwrap();
        assert_eq!(report.curve.knots, reference.knots);
        for &k in &interior {
            let expected = if k == interior[1] { 3 } else { 2 };
            assert_eq!(
                report.curve.knots.iter().filter(|&&v| v == k).count(),
                expected
            );
        }
        let deviation = max_deviation(&report.curve, &reference);
        assert!(deviation < 1e-9, "deviation {deviation}");
        // Repeating a clamped endpoint is beyond degree+1 and must fail.
        let target = target_knots(&curve, &[0.]);
        let error = refine_oslo(&curve, &target, usize::MAX).unwrap_err();
        assert_eq!(error.code, crate::INVALID_INPUT);
    }
}
