//! Triangle-mesh solid kernel: primitives, boolean, modeling, section.
pub mod boolean;
pub mod brep;
pub mod bvh;
pub mod bvh_query;
pub mod edges;
pub mod edit;
pub mod export_file;
pub mod export_prepare;
pub mod lineage;
pub mod modeling;
pub mod placement;
pub mod primitives;
pub mod program;
pub mod profile_program;
pub mod proximity;
pub mod scene_bvh;
pub mod section;
pub mod tessellation;
