[package]
name = "gcode-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
crc32fast = "=1.5.2"
math-core = { package = "osv-math", path = "../math-core" }

[dev-dependencies]
rbench = { workspace = true }

[[example]]
name = "bench_print_export"
path = "examples/bench_print_export.rs"
