[package]
name = "subdivision-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
math-core = { package = "osv-math", path = "../math-core" }
value-codec = { path = "../value-codec" }
geometry-ops = { path = "../geometry-ops" }
rustc-hash = "=2.1.1"
