[package]
name = "subdivision-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = ["codec"]
codec = ["dep:value-codec", "geometry-ops/codec"]

[dependencies]
math-core = { workspace = true }
value-codec = { workspace = true, optional = true }
geometry-ops = { workspace = true }
rustc-hash = "=2.1.1"
