[package]
name = "compute-cuda"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
gpu-compute = { path = "../gpu-compute", features = ["cuda"] }
tensor-core = { path = "../tensor-core" }

[dev-dependencies]
tensor-core = { path = "../tensor-core", features = ["conformance"] }
