#include <mlx/c/fast.h>
#include <mlx/c/ops.h>
#include <mlx/c/device.h>
#include <mlx/c/error.h>
#include <mlx/c/version.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
static void error(const char *m,void *p){fprintf(stderr,"MLX: %s\n",m);}
#define CHECK(x) do{if(x){fprintf(stderr,"failure line %d\n",__LINE__);exit(3);}}while(0)
int main(){mlx_set_error_handler(error,NULL,NULL);mlx_device device=mlx_device_new_type(MLX_GPU,0);bool available=false;CHECK(mlx_device_is_available(&available,device));if(!available)return 2;mlx_stream stream=mlx_stream_new_device(device);mlx_string ver=mlx_string_new();CHECK(mlx_version(&ver));printf("MLX %s GPU atomic-output linked-list probe\n",mlx_string_data(ver));mlx_string_free(ver);
 const unsigned n=65539,extent=17,total=(n+extent+255)/256*256;unsigned *indices=malloc(n*4);for(unsigned i=0;i<n;i++)indices[i]=i%11==0?~0u:i%extent;int shape[]={(int)n};mlx_array input=mlx_array_new_data(indices,shape,1,MLX_UINT32);const char *names[]={"indices"},*onames[]={"out"};mlx_vector_string ins=mlx_vector_string_new_data(names,1),ons=mlx_vector_string_new_data(onames,1);const char *source="for(ulong i=thread_position_in_grid.x;i<ulong(indices_shape[0]);i+=threads_per_grid.x){uint d=indices[i];if(d<17){uint old=atomic_exchange_explicit(&out[d],uint(i+1),memory_order_relaxed);atomic_store_explicit(&out[17+i],old,memory_order_relaxed);}}";mlx_fast_metal_kernel kernel=mlx_fast_metal_kernel_new("low_scatter_atomic_list_probe_v1",ins,ons,source,"",false,true);if(!kernel.ctx)return 4;mlx_vector_string_free(ins);mlx_vector_string_free(ons);mlx_fast_metal_kernel_config config=mlx_fast_metal_kernel_config_new();int outshape[]={(int)(total/256),256};CHECK(mlx_fast_metal_kernel_config_add_output_arg(config,outshape,2,MLX_UINT32));CHECK(mlx_fast_metal_kernel_config_set_grid(config,65536,1,1));CHECK(mlx_fast_metal_kernel_config_set_thread_group(config,256,1,1));CHECK(mlx_fast_metal_kernel_config_set_init_value(config,0));mlx_vector_array inputs=mlx_vector_array_new_value(input),outputs=mlx_vector_array_new();CHECK(mlx_fast_metal_kernel_apply(&outputs,kernel,inputs,config,stream));mlx_array result=mlx_array_new();CHECK(mlx_vector_array_get(&result,outputs,0));mlx_vector_array_free(inputs);mlx_vector_array_free(outputs);mlx_fast_metal_kernel_config_free(config);mlx_fast_metal_kernel_free(kernel);mlx_array_free(input);CHECK(mlx_array_eval(result));const uint32_t *data=mlx_array_data_uint32(result);unsigned *seen=calloc(n,4);unsigned errors=0,visited=0,expected=0;for(unsigned i=0;i<n;i++)if(indices[i]<extent)expected++;for(unsigned d=0;d<extent;d++){unsigned node=data[d],steps=0;while(node){if(node>n||steps++>=n){errors++;break;}unsigned i=node-1;if(indices[i]!=d||seen[i]++)errors++;visited++;node=data[extent+i];}}for(unsigned i=0;i<n;i++)if(seen[i]!=(indices[i]<extent))errors++;for(unsigned i=extent+n;i<total;i++)if(data[i]!=0)errors++;printf("indices=%u extent=%u valid=%u visited=%u errors=%u padded_words=%u\n",n,extent,expected,visited,errors,total-extent-n);mlx_array_free(result);mlx_synchronize(stream);mlx_stream_free(stream);mlx_device_free(device);free(indices);free(seen);return errors?1:0;}
