[package]
name = "bridge-analysis"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
bridge-codec = { path = "../bridge-codec" }
value-codec = { path = "../value-codec" }
mechanics-core = { path = "../mechanics-core" }
planar-geometry = { path = "../planar-geometry" }
polygon-core = { path = "../polygon-core" }
mesh-section = { workspace = true }
