pub(super) fn signature(name: &str) -> Option<&'static [&'static str]> {
    Some(match name {
        "polygon" => &["points"],
        "polygon_profile" => &["outer", "holes"],
        "polygon_extrude" => &["vector"],
        "polygon_sweep" => &["path", "up"],
        "polygon_loft" => &["sections"],
        "triangle_mesh" => &["vertices", "triangles"],
        "mesh_to_nurbs_brep" => &[],
        "mesh_to_sdf" => &[],
        "mesh_to_subdivision" => &["iterations"],
        "subdivision_tessellate" => &["levels"],
        "mesh_to_nurbs" => &[],
        "mesh_fit_nurbs" => &["max_deviation"],
        "nurbs_patches_tessellate" => &["segments"],
        "subdivision" => &["vertices", "faces", "levels"],
        "sdf_sphere" => &["center", "radius"],
        "sdf_box" => &["center", "half_size"],
        "sdf_torus" => &["center", "major_radius", "minor_radius"],
        "sdf_tessellate" => &["min", "max", "cells"],
        "sdf_offset" => &["distance"],
        "sdf_translate" => &["vector"],
        "brep_box" => &["min", "max"],
        "brep_sphere" => &["radius"],
        "brep_torus" => &["major_radius", "minor_radius"],
        "brep_cylinder" => &["radius", "height"],
        "brep_frustum" => &["bottom_radius", "top_radius", "height"],
        "brep_tube" => &["outer_radius", "inner_radius", "height"],
        "brep_gear" => &[
            "module",
            "teeth",
            "height",
            "pressure_angle",
            "helix_angle",
            "herringbone",
            "bore",
            "internal",
            "rim_width",
            "clearance",
            "backlash",
        ],
        "brep_revolve" => &["angle"],
        "brep_extrude" => &["height"],
        "brep_extrude_curves" => &["loops", "z_min", "z_max"],
        "brep_chamfer" => &["edges", "size"],
        "brep_fillet" => &["edges", "radius", "segments"],
        "brep_tessellate" => &["segments"],
        "brep_smooth_miter_stations" => &["wall_tolerance","quantum","max_work","max_deviation"],
        "nurbs_surface" => &[
            "degree_u",
            "degree_v",
            "knots_u",
            "knots_v",
            "control_points",
            "weights",
        ],
        "nurbs_curve" => &["degree", "knots", "control_points", "weights", "periodic"],
        "parabola_curve" | "hyperbola_curve" => &["center", "axis_u", "axis_v", "start", "end"],
        "elliptic_cylinder_surface" => &["center", "radius_x", "radius_y", "height"],
        "cone_frustum_surface" => &["center", "bottom_radius", "top_radius", "height"],
        "quadratic_patch" => &["bounds", "coefficients"],
        "line_curve" => &["start", "end"],
        "bezier_curve" => &["points", "weights"],
        "round_polyline_curve" => &["points", "radius", "closed"],
        "transition_polyline_curve" => &["points", "setback", "closed"],
        "closed_spline_curve" => &["points", "parameters"],
        "clamped_spline_curve" => &["points", "parameters", "start_tangent", "end_tangent"],
        "natural_spline_curve" => &["points", "parameters"],
        "hermite_curve" => &["points", "tangents", "parameters"],
        "clothoid_curve" => &["center", "length", "start_curvature", "end_curvature", "phase_degrees", "max_deviation"],
        "spherical_spiral_curve" => &["center", "radius", "longitude_turns", "latitude_turns", "longitude_phase_degrees", "latitude_phase_degrees", "max_deviation"],
        "toroidal_spiral_curve" => &["center", "major_radius", "minor_radius", "major_turns", "minor_turns", "major_phase_degrees", "minor_phase_degrees", "max_deviation"],
        "torus_knot_curve" => &["center", "major_radius", "minor_radius", "p", "q", "major_phase_degrees", "minor_phase_degrees", "max_deviation"],
        "helicoid_patches" => &["center", "inner_radius", "outer_radius", "height", "turns", "phase_degrees", "max_deviation"],
        "circle_rectangle_transition" => &["circle_center","circle_normal","circle_seam","circle_radius","rectangle_center","rectangle_axis_u","rectangle_axis_v"],
        "ellipse_transition_surface" => &["start_center","start_axis_u","start_axis_v","end_center","end_axis_u","end_axis_v"],
        "circle_transition_surface" => &["start_center","start_normal","start_seam","start_radius","end_center","end_normal","end_seam","end_radius"],
        "helicoid_surface" => &["center", "inner_radius", "outer_radius", "height", "turns", "phase_degrees", "max_deviation"],
        "catenoid_patches" => &["center", "scale", "start_z", "end_z", "max_deviation"],
        "catenoid_surface" => &["center", "scale", "start_z", "end_z", "max_deviation"],
        "catenary_curve" => &["center", "scale", "start_x", "end_x", "max_deviation"],
        "archimedean_spiral_curve" => &["center", "start_radius", "end_radius", "start_degrees", "end_degrees", "max_deviation"],
        "epicycloid_curve" => &["center", "fixed_radius", "rolling_radius", "start_degrees", "end_degrees", "max_deviation"],
        "hypocycloid_curve" => &["center", "fixed_radius", "rolling_radius", "start_degrees", "end_degrees", "max_deviation"],
        "trochoid_curve" => &["center", "rolling_radius", "tracing_radius", "start_degrees", "end_degrees", "max_deviation"],
        "cycloid_curve" => &["center", "radius", "start_degrees", "end_degrees", "max_deviation"],
        "lissajous_curve" => &["center", "amplitudes", "frequencies", "phases_degrees", "max_deviation"],
        "logarithmic_spiral_curve" => &["center", "radius", "growth", "start_degrees", "end_degrees", "max_deviation"],
        "involute_curve" => &["center", "radius", "start_degrees", "end_degrees", "max_deviation"],
        "helix_curve" => &["center", "radius", "height", "turns", "phase_degrees", "max_deviation"],
        "elliptic_helix_curve" => &["center", "radius_x", "radius_y", "height", "turns", "phase_degrees", "max_deviation"],
        "variable_pitch_helix_curve" => &["center", "radius", "height", "turns", "start_pitch", "end_pitch", "phase_degrees", "max_deviation"],
        "conical_helix_curve" => &["center", "start_radius", "end_radius", "height", "turns", "phase_degrees", "max_deviation"],
        "formula_curve" | "formula_surface" => &["domain", "expressions"],
        "sphere_surface" => &["center", "radius"],
        "cylinder_surface" | "cone_surface" => &["center", "radius", "height"],
        "plane_patch" => &["origin", "axis_u", "axis_v"],
        "grid_spline_surface" => &["points", "parameters_u", "parameters_v"],
        "hermite_patch" => &["corners", "tangent_u", "tangent_v", "twist"],
        "bilinear_patch" => &["corners"],
        "bezier_surface" => &["points", "weights"],
        "polyline_curve" => &["points", "closed"],
        "circle_curve" => &["center", "normal", "radius"],
        "circle_arc" => &["center", "normal", "radius", "start_degrees", "sweep_degrees"],
        "hyperboloid_one_sheet" => &["center", "radii", "start", "end"],
        "hyperboloid_two_sheet" => &["center", "radii", "start", "end", "lower"],
        "polynomial_graph" => &["bounds", "coefficients"],
        "polynomial_curve" | "polynomial_surface" | "rational_polynomial_curve" | "rational_polynomial_surface" => &["domain", "coefficients"],
        "ellipse_arc" => &["center", "axis_u", "axis_v", "start_degrees", "sweep_degrees"],
        "ellipsoid_surface" => &["center", "radii"],
        "torus_surface" => &["center", "major_radius", "radial_radius", "axial_radius"],
        "ribbon_surface" => &["width_law", "normal", "sections", "max_deviation"],
        "variable_pipe_surface" => &["radius_law", "normal", "sections", "max_deviation"],
        "pipe_surface" => &["radius", "normal", "sections", "max_deviation"],
        "screw_surface" => &["origin", "axis", "height", "turns", "phase_degrees", "max_deviation"],
        "surface_extrude_patches" => &["vector"],
        "surface_extrude" => &["vector"],
        "surface_revolve" => &["origin", "axis", "angle"],
        "tessellate" => &["segments_u", "segments_v"],
        "thicken" => &["vector"],
        "transform" => &["matrix"],
        "gear" => &[
            "teeth",
            "module",
            "thickness",
            "pressure_angle",
            "bore",
            "backlash",
            "clearance",
            "internal",
            "rim_width",
            "flank_segments",
            "helix_angle",
            "herringbone",
        ],
        "planetary_gears" => &[
            "sun_teeth",
            "planet_teeth",
            "planet_count",
            "module",
            "thickness",
            "pressure_angle",
            "bore",
            "backlash",
            "clearance",
            "rim_width",
            "flank_segments",
            "carrier_angle",
            "helix_angle",
            "herringbone",
        ],
        "planetary_spinner" => &[
            "inner_radius",
            "outer_radius",
            "bore",
            "gap",
            "height",
            "helix_angle",
        ],
        "circle" => &["radius"],
        "rectangle" => &["size"],
        "box" => &["size"],
        "sphere" => &["radius"],
        "cylinder" => &["radius", "height"],
        "extrude" => &["height"],
        "revolve" => &["angle"],
        "translate" => &["vector"],
        "rotate" => &["vector"],
        "scale" => &["vector"],
        "offset" => &["distance"],
        "mirror" => &["normal"],
        _ => return None,
    })
}
