[package]
name = "slicer-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
math-core = { package = "osv-math", path = "../math-core" }
gcode-core = { path = "../gcode-core" }
planar-geometry = { path = "../planar-geometry" }

[dev-dependencies]
polygon-core = { path = "../polygon-core" }
