[package]
name = "slicer-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
math-core = { workspace = true }
gcode-core = { workspace = true }
gcode-optimize = { workspace = true }
planar-geometry = { workspace = true }

[dev-dependencies]
polygon-core = { workspace = true }
gcode-core = { workspace = true }
