import { spawnSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import { reproducibleCargo } from './reproducible-cargo.mjs'

const root = fileURLToPath(new URL('..', import.meta.url))
const target = resolve(root, 'crates/target')
const reproducible = reproducibleCargo(root)
const result = spawnSync('cargo', ['build', '--config', 'profile.release.strip="symbols"', ...reproducible.args, '--locked', '--release', '--target', 'wasm32-unknown-unknown', '--manifest-path', 'crates/Cargo.toml', '-p', 'vr-core'], {
  cwd: root, stdio: 'inherit', env: { ...process.env, ...reproducible.env, CARGO_TARGET_DIR: target },
})
if (result.error) throw result.error
if (result.status !== 0) process.exit(result.status ?? 1)
const bytes = readFileSync(resolve(target, 'wasm32-unknown-unknown/release/vr_core.wasm'))
if (WebAssembly.Module.imports(new WebAssembly.Module(bytes)).length) throw new Error('VR kernel must be self-contained')
const dir = resolve(root, 'src/generated/vr-core')
mkdirSync(dir, { recursive: true })
writeFileSync(resolve(dir, 'bytes.ts'), `// Generated by scripts/build-vr.mjs; do not edit.\nexport default '${bytes.toString('base64')}'\n`)
console.log(`vr-core: ${bytes.length} WASM bytes`)
