[package]
name = "photogrammetry-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
gpu = ["dep:gpu-compute", "dep:compute-core", "dep:math-compute", "math-compute/gpu"]
cuda = ["gpu", "math-compute/cuda"]

[dependencies]
math-core = { package = "osv-math", path = "../math-core" }
math-compute = { package = "osv-math-compute", path = "../math-compute", optional = true }
compute-core = { path = "../compute-core", optional = true }
gpu-compute = { path = "../gpu-compute", optional = true }

[dev-dependencies]
rbench = { workspace = true }

[[example]]
name = "bench_matching"
path = "examples/bench_matching.rs"
