[package]
name = "photogrammetry-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
gpu = ["dep:gpu-compute", "math-core/gpu"]
cuda = ["gpu", "math-core/cuda"]

[dependencies]
math-core = { package = "osv-math", path = "../math-core" }
gpu-compute = { path = "../gpu-compute", optional = true }

[dev-dependencies]
rbench = { workspace = true }

[[example]]
name = "bench_matching"
path = "examples/bench_matching.rs"
