// Constants generated by tools/generate-binary64-constants.py; integer words only.
const D64_ONE: D64 = D64(0x00000000u,0x3ff00000u);
const D64_HALF: D64 = D64(0x00000000u,0x3fe00000u);
const D64_TWO: D64 = D64(0x00000000u,0x40000000u);
const D64_LN2: D64 = D64(0xfefa39efu,0x3fe62e42u);
const D64_LN2_HI: D64 = D64(0xfee00000u,0x3fe62e42u);
const D64_LN2_LO: D64 = D64(0x35793c76u,0x3dea39efu);
const D64_PIO2: D64 = D64(0x54442d18u,0x3ff921fbu);
const D64_PIO2_LO: D64 = D64(0x33145c07u,0x3c91a626u);
const D64_SQRT2: D64 = D64(0x667f3bcdu,0x3ff6a09eu);
const D64_TWO_OVER_PI: array<u32,80> = array<u32,80>(13853u,39668u,48160u,61647u,27563u,64635u,12358u,22019u,23816u,8077u,24497u,27643u,37610u,35410u,14839u,15623u,61819u,60389u,47815u,29991u,59949u,40543u,16230u,20294u,2487u,10187u,32463u,27958u,27935u,23050u,4491u,61231u,38927u,56837u,38911u,8184u,10299u,48633u,24459u,40068u,14836u,33619u,54841u,14737u,32321u,46175u,28710u,59804u,17540u,11963u,13813u,59522u,42814u,45353u,60188u,65053u,37404u,2513u,12010u,1609u,53984u,16973u,28218u,46884u,50529u,57019u,25515u,65105u,36929u,15427u,38297u,56162u,56768u,62772u,22481u,64551u,5417u,20036u,33646u,41721u);
fn d64_exp_poly(x:D64)->D64 {
 var value=D64(0xa4020225u,0x3c1e542bu);
 value=d64_add(D64(0x46814157u,0x3c62f49bu),d64_mul(x,value));
 value=d64_add(D64(0x63b97d97u,0x3ca68278u),d64_mul(x,value));
 value=d64_add(D64(0x7030ad4au,0x3ce952c7u),d64_mul(x,value));
 value=d64_add(D64(0xe733b81fu,0x3d2ae7f3u),d64_mul(x,value));
 value=d64_add(D64(0xe733b81fu,0x3d6ae7f3u),d64_mul(x,value));
 value=d64_add(D64(0xa8c07c9du,0x3da93974u),d64_mul(x,value));
 value=d64_add(D64(0x13a86d09u,0x3de61246u),d64_mul(x,value));
 value=d64_add(D64(0xeff8d898u,0x3e21eed8u),d64_mul(x,value));
 value=d64_add(D64(0x67f544e4u,0x3e5ae645u),d64_mul(x,value));
 value=d64_add(D64(0xb7789f5cu,0x3e927e4fu),d64_mul(x,value));
 value=d64_add(D64(0xa556c734u,0x3ec71de3u),d64_mul(x,value));
 value=d64_add(D64(0x1a01a01au,0x3efa01a0u),d64_mul(x,value));
 value=d64_add(D64(0x1a01a01au,0x3f2a01a0u),d64_mul(x,value));
 value=d64_add(D64(0x16c16c17u,0x3f56c16cu),d64_mul(x,value));
 value=d64_add(D64(0x11111111u,0x3f811111u),d64_mul(x,value));
 value=d64_add(D64(0x55555555u,0x3fa55555u),d64_mul(x,value));
 value=d64_add(D64(0x55555555u,0x3fc55555u),d64_mul(x,value));
 value=d64_add(D64(0x00000000u,0x3fe00000u),d64_mul(x,value));
 value=d64_add(D64(0x00000000u,0x3ff00000u),d64_mul(x,value));
 value=d64_add(D64(0x00000000u,0x3ff00000u),d64_mul(x,value));
 return value;
}
fn d64_log_poly(x:D64)->D64 {
 var value=D64(0xbda12f68u,0x3fa2f684u);
 value=d64_add(D64(0x47ae147bu,0x3fa47ae1u),d64_mul(x,value));
 value=d64_add(D64(0x590b2164u,0x3fa642c8u),d64_mul(x,value));
 value=d64_add(D64(0x18618618u,0x3fa86186u),d64_mul(x,value));
 value=d64_add(D64(0xbca1af28u,0x3faaf286u),d64_mul(x,value));
 value=d64_add(D64(0x1e1e1e1eu,0x3fae1e1eu),d64_mul(x,value));
 value=d64_add(D64(0x11111111u,0x3fb11111u),d64_mul(x,value));
 value=d64_add(D64(0x13b13b14u,0x3fb3b13bu),d64_mul(x,value));
 value=d64_add(D64(0x745d1746u,0x3fb745d1u),d64_mul(x,value));
 value=d64_add(D64(0x1c71c71cu,0x3fbc71c7u),d64_mul(x,value));
 value=d64_add(D64(0x92492492u,0x3fc24924u),d64_mul(x,value));
 value=d64_add(D64(0x9999999au,0x3fc99999u),d64_mul(x,value));
 value=d64_add(D64(0x55555555u,0x3fd55555u),d64_mul(x,value));
 value=d64_add(D64(0x00000000u,0x3ff00000u),d64_mul(x,value));
 return value;
}
fn d64_sin_poly(x:D64)->D64 {
 var value=D64(0x46814157u,0xbc62f49bu);
 value=d64_add(D64(0x7030ad4au,0x3ce952c7u),d64_mul(x,value));
 value=d64_add(D64(0xe733b81fu,0xbd6ae7f3u),d64_mul(x,value));
 value=d64_add(D64(0x13a86d09u,0x3de61246u),d64_mul(x,value));
 value=d64_add(D64(0x67f544e4u,0xbe5ae645u),d64_mul(x,value));
 value=d64_add(D64(0xa556c734u,0x3ec71de3u),d64_mul(x,value));
 value=d64_add(D64(0x1a01a01au,0xbf2a01a0u),d64_mul(x,value));
 value=d64_add(D64(0x11111111u,0x3f811111u),d64_mul(x,value));
 value=d64_add(D64(0x55555555u,0xbfc55555u),d64_mul(x,value));
 value=d64_add(D64(0x00000000u,0x3ff00000u),d64_mul(x,value));
 return value;
}
fn d64_cos_poly(x:D64)->D64 {
 var value=D64(0xa4020225u,0x3c1e542bu);
 value=d64_add(D64(0x63b97d97u,0xbca68278u),d64_mul(x,value));
 value=d64_add(D64(0xe733b81fu,0x3d2ae7f3u),d64_mul(x,value));
 value=d64_add(D64(0xa8c07c9du,0xbda93974u),d64_mul(x,value));
 value=d64_add(D64(0xeff8d898u,0x3e21eed8u),d64_mul(x,value));
 value=d64_add(D64(0xb7789f5cu,0xbe927e4fu),d64_mul(x,value));
 value=d64_add(D64(0x1a01a01au,0x3efa01a0u),d64_mul(x,value));
 value=d64_add(D64(0x16c16c17u,0xbf56c16cu),d64_mul(x,value));
 value=d64_add(D64(0x55555555u,0x3fa55555u),d64_mul(x,value));
 value=d64_add(D64(0x00000000u,0xbfe00000u),d64_mul(x,value));
 value=d64_add(D64(0x00000000u,0x3ff00000u),d64_mul(x,value));
 return value;
}
