[package]
name = "modelgraph-text"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
math-core = { workspace = true }
value-codec = { workspace = true }
themoretheless-tokenizer-rush = { git = "https://github.com/themoretheless/tokenizer.git", branch = "release" }
